# Generated by Django 5.2.8 on 2026-01-22 04:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_core', '0004_alter_country_code'),
        ('finance_gl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(help_text="Unique budget code, e.g., 'FY2026-OPERATING'", max_length=50, unique=True)),
                ('budget_name', models.CharField(help_text="Descriptive budget name, e.g., 'FY 2026 Operating Budget'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about this budget')),
                ('start_date', models.DateField(help_text='Budget effective start date')),
                ('end_date', models.DateField(help_text='Budget effective end date')),
                ('default_control_level', models.CharField(choices=[('NONE', 'No Control'), ('TRACK', 'Track'), ('ADVISORY', 'Advisory'), ('ABSOLUTE', 'Absolute Control')], default='ABSOLUTE', help_text='Default budget control enforcement level (can be overridden per segment)', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Is this budget currently active for budget checking?')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this budget')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.CharField(blank=True, max_length=100)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(help_text='Budget currency (base currency only)', on_delete=django.db.models.deletion.PROTECT, to='finance_core.currency')),
            ],
            options={
                'db_table': 'budget_header',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetSegmentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_level', models.CharField(blank=True, choices=[('NONE', 'No Control'), ('TRACK_ONLY', 'Track Only'), ('ADVISORY', 'Advisory'), ('ABSOLUTE', 'Absolute Control')], help_text='Override control level for this segment. If NULL, uses budget_header.default_control_level', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this segment value active for budget checking?')),
                ('notes', models.TextField(blank=True, help_text="Notes or reason for this segment's control level")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_header', models.ForeignKey(help_text='Parent budget header', on_delete=django.db.models.deletion.CASCADE, related_name='budget_segment_values', to='budget_control.budgetheader')),
                ('segment_value', models.ForeignKey(help_text='Segment value to budget on (e.g., Account 5000, Department 1, Project PROJ1)', on_delete=django.db.models.deletion.PROTECT, related_name='budget_segment_values', to='finance_gl.xx_segment')),
            ],
            options={
                'db_table': 'budget_segment_value',
                'ordering': ['budget_header', 'segment_value'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_budget', models.DecimalField(decimal_places=2, help_text='Original budget allocation for this segment value', max_digits=15)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget adjustments (positive or negative). AUTO-UPDATED by budget amendments.', max_digits=15)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount committed via approved PRs (Purchase Requisitions - Stage 1). AUTO-UPDATED by system.', max_digits=15)),
                ('encumbered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount encumbered via approved POs (Purchase Orders - Stage 2). AUTO-UPDATED by system.', max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually spent via approved/posted invoices (Stage 3). AUTO-UPDATED by system.', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Notes or justification for this budget amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_committed_date', models.DateTimeField(blank=True, help_text='Last time budget was committed via PR (Stage 1)', null=True)),
                ('last_encumbered_date', models.DateTimeField(blank=True, help_text='Last time budget was encumbered via PO (Stage 2)', null=True)),
                ('last_actual_date', models.DateTimeField(blank=True, help_text='Last time budget was consumed by actual spending via Invoice (Stage 3)', null=True)),
                ('last_adjustment_date', models.DateTimeField(blank=True, help_text='Last time budget was adjusted', null=True)),
                ('budget_header', models.ForeignKey(help_text='Parent budget header (for easier querying)', on_delete=django.db.models.deletion.CASCADE, related_name='budget_amounts', to='budget_control.budgetheader')),
                ('budget_segment_value', models.OneToOneField(help_text='Links to segment value definition (includes control level)', on_delete=django.db.models.deletion.CASCADE, related_name='budget_amount', to='budget_control.budgetsegmentvalue')),
            ],
            options={
                'db_table': 'budget_amount',
                'ordering': ['budget_header'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetheader',
            index=models.Index(fields=['status', 'is_active'], name='budget_head_status_1adef8_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetheader',
            index=models.Index(fields=['budget_code'], name='budget_head_budget__d260b7_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetheader',
            index=models.Index(fields=['start_date', 'end_date'], name='budget_head_start_d_c61274_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetsegmentvalue',
            index=models.Index(fields=['budget_header', 'segment_value'], name='budget_segm_budget__3f2634_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetsegmentvalue',
            index=models.Index(fields=['is_active'], name='budget_segm_is_acti_b5623c_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetsegmentvalue',
            constraint=models.UniqueConstraint(fields=('budget_header', 'segment_value'), name='unique_segment_value_per_budget'),
        ),
        migrations.AddIndex(
            model_name='budgetamount',
            index=models.Index(fields=['budget_header', 'budget_segment_value'], name='budget_amou_budget__042ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetamount',
            index=models.Index(fields=['budget_segment_value'], name='budget_amou_budget__ce8e02_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetamount',
            constraint=models.UniqueConstraint(fields=('budget_header', 'budget_segment_value'), name='unique_budget_per_segment_value'),
        ),
    ]
