# Generated by Django 5.2.8 on 2025-12-15 11:31

import Finance.core.base_models
import core.approval.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_pr', models.CharField(choices=[('Catalog', 'Catalog'), ('Non-Catalog', 'Non-Catalog'), ('Service', 'Service')], default='Catalog', help_text='Type of purchase requisition', max_length=20)),
                ('pr_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField()),
                ('required_date', models.DateField(help_text='Date when items/services are needed')),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_department', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CONVERTED_TO_PO', 'Converted to PO')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line items before tax', max_digits=14)),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, help_text='Name of approver', max_length=255)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, help_text='Name of rejector', max_length=255)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, help_text='Overall PR description')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'db_table': 'pr',
                'ordering': ['-date', '-created_at'],
            },
            bases=(core.approval.mixins.ApprovableInterface, models.Model),
        ),
        migrations.CreateModel(
            name='Catalog_PR',
            fields=[
                ('pr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_pr', serialize=False, to='PR.pr')),
            ],
            options={
                'verbose_name': 'Catalog PR',
                'verbose_name_plural': 'Catalog PRs',
                'db_table': 'catalog_pr',
            },
            bases=(Finance.core.base_models.ChildModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NonCatalog_PR',
            fields=[
                ('pr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='noncatalog_pr', serialize=False, to='PR.pr')),
            ],
            options={
                'verbose_name': 'Non-Catalog PR',
                'verbose_name_plural': 'Non-Catalog PRs',
                'db_table': 'noncatalog_pr',
            },
            bases=(Finance.core.base_models.ChildModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service_PR',
            fields=[
                ('pr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='service_pr', serialize=False, to='PR.pr')),
            ],
            options={
                'verbose_name': 'Service PR',
                'verbose_name_plural': 'Service PRs',
                'db_table': 'service_pr',
            },
            bases=(Finance.core.base_models.ChildModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, help_text='Line item sequence number')),
                ('item_name', models.CharField(help_text='Item/Service name', max_length=255)),
                ('item_description', models.TextField(blank=True, help_text='Detailed description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Item quantity', max_digits=14)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Estimated price per unit', max_digits=14)),
                ('total_price_per_item', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated: estimated_unit_price * quantity', max_digits=14)),
                ('notes', models.TextField(blank=True, help_text='Item-specific notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(blank=True, help_text='Link to catalog item (for Catalog PRs or as category reference)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pr_items', to='catalog.catalogitem')),
                ('pr', models.ForeignKey(help_text='Parent PR', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='PR.pr')),
                ('unit_of_measure', models.ForeignKey(blank=True, help_text='Unit of measure (EA, KG, M, L, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure')),
            ],
            options={
                'verbose_name': 'PR Item',
                'verbose_name_plural': 'PR Items',
                'db_table': 'pr_item',
                'ordering': ['pr', 'line_number'],
                'unique_together': {('pr', 'line_number')},
            },
        ),
    ]
