# Generated by Django 5.2.8 on 2025-12-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pritem',
            name='conversion_date',
            field=models.DateTimeField(blank=True, help_text='When this line was converted to PO', null=True),
        ),
        migrations.AddField(
            model_name='pritem',
            name='converted_to_po',
            field=models.BooleanField(default=False, help_text='Whether this line has been fully converted to a PO'),
        ),
        migrations.AddField(
            model_name='pritem',
            name='quantity_converted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity converted to POs', max_digits=14),
        ),
    ]
