# Generated by Django 5.2.8 on 2026-01-14 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR', '0002_pritem_conversion_date_pritem_converted_to_po_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type or file extension', max_length=100)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_data', models.BinaryField(help_text='Binary file data (BLOB)')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='Name of user who uploaded the attachment', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment')),
                ('pr', models.ForeignKey(help_text='Parent PR', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='PR.pr')),
            ],
            options={
                'db_table': 'pr_attachment',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['pr', '-upload_date'], name='pr_attachme_pr_id_e5bdca_idx')],
            },
        ),
    ]
