# Generated by Django 5.2.8 on 2026-01-22 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR', '0003_prattachment'),
        ('finance_gl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='budget_check_message',
            field=models.TextField(blank=True, help_text='Budget check details or warnings'),
        ),
        migrations.AddField(
            model_name='pr',
            name='budget_check_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not Checked'), ('PASSED', 'Passed'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], default='NOT_CHECKED', help_text='Budget check result', max_length=20),
        ),
        migrations.AddField(
            model_name='pr',
            name='budget_committed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when budget commitment was created', null=True),
        ),
        migrations.AddField(
            model_name='pr',
            name='segment_combination',
            field=models.ForeignKey(blank=True, help_text='GL account coding for budget control - applies to ALL line items in this PR', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='finance_gl.xx_segment_combination'),
        ),
    ]
