# Generated by Django 5.2.8 on 2025-12-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='UoM code (e.g., PCS, KG)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name (e.g., Pieces, Kilograms)', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('uom_type', models.CharField(choices=[('QUANTITY', 'Quantity'), ('WEIGHT', 'Weight'), ('LENGTH', 'Length'), ('AREA', 'Area'), ('VOLUME', 'Volume')], default='QUANTITY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['code'],
            },
        ),
    ]
