# Generated by Django 5.2.8 on 2025-12-27 13:32

import django.db.models.deletion
import HR.work_structures.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('has_range', models.BooleanField(default=True, help_text='True for min/max range (e.g., Basic Salary), False for fixed value (e.g., Transportation)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grade Rate Type',
                'verbose_name_plural': 'Grade Rate Types',
                'db_table': 'hr_grade_rate_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
                'ordering': ['-effective_start_date', 'name'],
                'indexes': [models.Index(fields=['code', 'effective_start_date'], name='work_struct_code_0e1e18_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'effective_start_date'), name='unique_enterprise_version')],
            },
            bases=(HR.work_structures.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_groups', to='work_structures.enterprise')),
            ],
            options={
                'verbose_name': 'Business Group',
                'verbose_name_plural': 'Business Groups',
                'ordering': ['-effective_start_date', 'enterprise', 'name'],
            },
            bases=(HR.work_structures.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_structures.businessgroup')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
            bases=(HR.work_structures.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GradeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount for range-based rates', max_digits=15, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount for range-based rates', max_digits=15, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for non-range rates', max_digits=15, null=True)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_levels', to='work_structures.grade')),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='work_structures.graderatetype')),
            ],
            options={
                'verbose_name': 'Grade Rate Level',
                'verbose_name_plural': 'Grade Rate Levels',
                'db_table': 'hr_grade_rate',
                'ordering': ['grade', 'rate_type', '-effective_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('address_details', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('business_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='work_structures.businessgroup')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='work_structures.enterprise')),
            ],
            bases=(HR.work_structures.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='work_structures.businessgroup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='work_structures.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='work_structures.location')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
            bases=(HR.work_structures.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_structures.department')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_structures.grade')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_structures.location')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='work_structures.position')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['code', '-effective_start_date'],
            },
            bases=(HR.work_structures.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserDataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='If true, user can access ALL Business Groups')),
                ('business_group', models.ForeignKey(blank=True, help_text='Business Group scope. If department is null, grants access to all departments in BG', null=True, on_delete=django.db.models.deletion.CASCADE, to='work_structures.businessgroup')),
                ('department', models.ForeignKey(blank=True, help_text='If set, restricts access to only this department within the BG', null=True, on_delete=django.db.models.deletion.CASCADE, to='work_structures.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_data_scopes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='work_structures.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Manager',
                'verbose_name_plural': 'Department Managers',
                'indexes': [models.Index(fields=['department', 'effective_start_date', 'effective_end_date'], name='work_struct_departm_65f75d_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'manager', 'effective_start_date'), name='unique_dept_manager_assignment')],
            },
        ),
        migrations.AddIndex(
            model_name='businessgroup',
            index=models.Index(fields=['enterprise', 'code', 'effective_start_date'], name='work_struct_enterpr_fe01a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessgroup',
            constraint=models.UniqueConstraint(fields=('enterprise', 'code', 'effective_start_date'), name='unique_bg_version_per_enterprise'),
        ),
        migrations.AddConstraint(
            model_name='graderate',
            constraint=models.UniqueConstraint(fields=('grade', 'rate_type', 'effective_start_date'), name='unique_grade_rate_effective_start'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', 'effective_start_date'], name='work_struct_code_b7e280_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['business_group'], name='work_struct_busines_d1fc63_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('business_group', 'code', 'effective_start_date'), name='unique_dept_version'),
        ),
        migrations.AddIndex(
            model_name='userdatascope',
            index=models.Index(fields=['user', 'is_global'], name='work_struct_user_id_b32d63_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatascope',
            index=models.Index(fields=['user', 'business_group'], name='work_struct_user_id_1a14be_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatascope',
            index=models.Index(fields=['user', 'department'], name='work_struct_user_id_e7c68a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdatascope',
            constraint=models.CheckConstraint(condition=models.Q(('is_global', True), ('business_group__isnull', False), _connector='OR'), name='scope_requires_bg_or_global'),
        ),
        migrations.AddConstraint(
            model_name='userdatascope',
            constraint=models.CheckConstraint(condition=models.Q(('department__isnull', True), ('business_group__isnull', False), _connector='OR'), name='dept_scope_requires_bg'),
        ),
        migrations.AddConstraint(
            model_name='userdatascope',
            constraint=models.UniqueConstraint(fields=('user', 'business_group', 'department'), name='unique_user_scope_combination'),
        ),
    ]
