# Generated by Django 5.2.8 on 2026-01-21 21:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status. Set to INACTIVE instead of deleting.', max_length=10)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('sequence', models.IntegerField(help_text='Numeric order of grade within business group (lower = more junior)')),
                ('effective_from', models.DateTimeField(blank=True, help_text='Effective from timestamp', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grade_name', models.ForeignKey(help_text='Grade name from lookup (e.g., Grade 1, Grade 2, Manager Level)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Grade Name'}, on_delete=django.db.models.deletion.PROTECT, related_name='grades_by_name', to='lookups.lookupvalue')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'hr_grade',
                'ordering': ['organization', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='GradeRateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('has_range', models.BooleanField(default=True, help_text='True for min/max range (e.g., Basic Salary), False for fixed value (e.g., Transportation)')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade Rate Type',
                'verbose_name_plural': 'Grade Rate Types',
                'db_table': 'hr_grade_rate_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(db_index=True, help_text='Job code (unique within version group)', max_length=50)),
                ('job_description', models.TextField(help_text='Detailed job description')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of job responsibilities (stored as JSON array)')),
                ('competencies', models.ManyToManyField(blank=True, help_text='Required competencies with proficiency levels', related_name='required_for_jobs', through='person.JobCompetencyRequirement', to='person.competency')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grades', models.ManyToManyField(blank=True, help_text='Valid grades for this job', related_name='jobs', to='work_structures.grade')),
                ('job_category', models.ForeignKey(help_text='Job category (e.g., Management, Technical, Administrative)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Job Category'}, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_by_category', to='lookups.lookupvalue')),
                ('job_title', models.ForeignKey(help_text='Job title (e.g., Software Engineer, Manager)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Job Title'}, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_by_title', to='lookups.lookupvalue')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'hr_job',
                'ordering': ['business_group', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JobQualificationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('is_mandatory', models.BooleanField(default=True, help_text='True if required, False if preferred')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_requirements', to='work_structures.job')),
                ('qualification_title', models.ForeignKey(help_text='Required qualification title (e.g., Computer Science, Business Administration)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Qualification Title'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('qualification_type', models.ForeignKey(help_text="Required qualification type (e.g., Bachelor's, Master's)", limit_choices_to={'is_active': True, 'lookup_type__name': 'Qualification Type'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Qualification Requirement',
                'verbose_name_plural': 'Job Qualification Requirements',
                'db_table': 'hr_job_qualification_requirement',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.ManyToManyField(blank=True, help_text='Required qualification types/titles', related_name='required_for_jobs', through='work_structures.JobQualificationRequirement', through_fields=('job', 'qualification_type'), to='lookups.lookupvalue'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status. Set to INACTIVE instead of deleting.', max_length=10)),
                ('location_name', models.CharField(db_index=True, help_text='Unique location name', max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, help_text='Street zone/district', max_length=100)),
                ('street', models.CharField(blank=True, help_text='Street name', max_length=200)),
                ('building', models.CharField(blank=True, help_text='Building number/name', max_length=100)),
                ('floor', models.CharField(blank=True, help_text='Floor number', max_length=50)),
                ('office', models.CharField(blank=True, help_text='Office number', max_length=50)),
                ('po_box', models.CharField(blank=True, help_text='PO Box', max_length=50)),
                ('effective_from', models.DateTimeField(blank=True, help_text='Effective from timestamp', null=True)),
                ('city', models.ForeignKey(blank=True, help_text='City lookup (must be child of selected country)', limit_choices_to={'is_active': True, 'lookup_type__name': 'City'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_by_city', to='lookups.lookupvalue')),
                ('country', models.ForeignKey(blank=True, help_text='Country lookup', limit_choices_to={'is_active': True, 'lookup_type__name': 'Country'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_by_country', to='lookups.lookupvalue')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'hr_location',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('organization_name', models.CharField(db_index=True, help_text='Unique organization name', max_length=50, unique=True)),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0), help_text='Work start time (e.g., 09:00)')),
                ('work_end_time', models.TimeField(default=datetime.time(17, 0), help_text='Work end time (e.g., 17:00)')),
                ('business_group', models.ForeignKey(blank=True, help_text='Root organization (null for business groups)', limit_choices_to={'business_group__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_organizations', to='work_structures.organization')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Primary location of organization', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='work_structures.location')),
                ('organization_type', models.ForeignKey(help_text='Organization type from lookup', limit_choices_to={'is_active': True, 'lookup_type__name': 'Organization Type'}, on_delete=django.db.models.deletion.PROTECT, related_name='organizations_by_type', to='lookups.lookupvalue')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'hr_organization',
                'ordering': ['organization_name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='business_group',
            field=models.ForeignKey(help_text='Root organization (Business Group) that owns this location', limit_choices_to={'business_group__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='work_structures.organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='business_group',
            field=models.ForeignKey(help_text='Root organization (Business Group) that owns this job', limit_choices_to={'business_group__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='work_structures.organization'),
        ),
        migrations.AddField(
            model_name='grade',
            name='organization',
            field=models.ForeignKey(help_text='Root organization (Business Group) that owns this grade', limit_choices_to={'business_group__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='work_structures.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization being managed', on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='work_structures.organization')),
                ('person', models.ForeignKey(help_text='Person who is the manager (must be an Employee)', on_delete=django.db.models.deletion.PROTECT, related_name='managed_organizations', to='person.person')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Manager',
                'verbose_name_plural': 'Organization Managers',
                'db_table': 'hr_organization_manager',
                'ordering': ['-effective_start_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(db_index=True, help_text='Position code (unique within version group)', max_length=50)),
                ('position_sync', models.BooleanField(default=False, help_text='Synchronization flag')),
                ('full_time_equivalent', models.DecimalField(decimal_places=2, default=1.0, help_text='FTE: 1.0 = full time, 0.5 = half time (range: 0.1-1.5)', max_digits=3)),
                ('head_count', models.IntegerField(default=1, help_text='Number of people for this position (headcount)')),
                ('competencies', models.ManyToManyField(blank=True, help_text='Required competencies with proficiency levels', related_name='required_for_positions', through='person.PositionCompetencyRequirement', to='person.competency')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, help_text='Grade/level for this position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='work_structures.grade')),
                ('job', models.ForeignKey(help_text='Job definition this position is based on', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='work_structures.job')),
                ('location', models.ForeignKey(blank=True, help_text='Physical location of position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='work_structures.location')),
                ('organization', models.ForeignKey(help_text='Organization (department/unit) where this position exists', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='work_structures.organization')),
                ('payroll', models.ForeignKey(blank=True, help_text='Payroll type', limit_choices_to={'is_active': True, 'lookup_type__name': 'Payroll'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions_by_payroll', to='lookups.lookupvalue')),
                ('position_status', models.ForeignKey(help_text='Position status (e.g., Active, Frozen, Eliminated)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Position Status'}, on_delete=django.db.models.deletion.PROTECT, related_name='positions_by_status', to='lookups.lookupvalue')),
                ('position_title', models.ForeignKey(help_text='Position title', limit_choices_to={'is_active': True, 'lookup_type__name': 'Position Title'}, on_delete=django.db.models.deletion.PROTECT, related_name='positions_by_title', to='lookups.lookupvalue')),
                ('position_type', models.ForeignKey(help_text='Position type (e.g., Regular, Temporary)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Position Type'}, on_delete=django.db.models.deletion.PROTECT, related_name='positions_by_type', to='lookups.lookupvalue')),
                ('reports_to', models.ForeignKey(blank=True, help_text='Reporting position (supervisory hierarchy)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='work_structures.position')),
                ('salary_basis', models.ForeignKey(blank=True, help_text='Salary basis (e.g., Monthly, Hourly)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Salary Basis'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions_by_salary_basis', to='lookups.lookupvalue')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'hr_position',
                'ordering': ['organization', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PositionQualificationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('is_mandatory', models.BooleanField(default=True, help_text='True if required, False if preferred')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_requirements', to='work_structures.position')),
                ('qualification_title', models.ForeignKey(help_text='Required qualification title (e.g., Computer Science, Business Administration)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Qualification Title'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('qualification_type', models.ForeignKey(help_text="Required qualification type (e.g., Bachelor's, Master's)", limit_choices_to={'is_active': True, 'lookup_type__name': 'Qualification Type'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position Qualification Requirement',
                'verbose_name_plural': 'Position Qualification Requirements',
                'db_table': 'hr_position_qualification_requirement',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='qualifications',
            field=models.ManyToManyField(blank=True, help_text='Required qualification types/titles', related_name='required_for_positions', through='work_structures.PositionQualificationRequirement', through_fields=('position', 'qualification_type'), to='lookups.lookupvalue'),
        ),
        migrations.CreateModel(
            name='GradeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount for range-based rates', max_digits=15, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount for range-based rates', max_digits=15, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for non-range rates', max_digits=15, null=True)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_levels', to='work_structures.grade')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='work_structures.graderatetype')),
            ],
            options={
                'verbose_name': 'Grade Rate Level',
                'verbose_name_plural': 'Grade Rate Levels',
                'db_table': 'hr_grade_rate',
                'ordering': ['grade', 'rate_type', '-effective_start_date'],
                'constraints': [models.UniqueConstraint(fields=('grade', 'rate_type', 'effective_start_date'), name='unique_grade_rate_effective_start')],
            },
        ),
        migrations.AddIndex(
            model_name='jobqualificationrequirement',
            index=models.Index(fields=['job'], name='hr_job_qual_job_id_afb485_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobqualificationrequirement',
            unique_together={('job', 'qualification_type', 'qualification_title')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['business_group', 'effective_start_date', 'effective_end_date'], name='hr_organiza_busines_9409fd_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_name'], name='hr_organiza_organiz_84e769_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['location'], name='hr_organiza_locatio_d064d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('work_end_time__gt', models.F('work_start_time'))), name='work_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['status', 'location_name'], name='hr_location_status_8eeffa_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['business_group', 'status'], name='hr_location_busines_9a9c11_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'city'], name='hr_location_country_043c86_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['business_group', 'effective_start_date', 'effective_end_date'], name='hr_job_busines_8c8db0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['code'], name='hr_job_code_aee124_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_category'], name='hr_job_job_cat_6aed3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('code', 'business_group', 'effective_start_date'), name='unique_job_code_bg_start_date'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['status', 'organization', 'sequence'], name='hr_grade_status_6f1b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['code'], name='hr_grade_code_6c2209_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('organization', 'sequence'), name='unique_grade_sequence_per_org'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('organization', 'code'), name='unique_active_grade_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='grade_sequence_positive'),
        ),
        migrations.AddIndex(
            model_name='organizationmanager',
            index=models.Index(fields=['organization', 'effective_start_date', 'effective_end_date'], name='hr_organiza_organiz_fc5439_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmanager',
            index=models.Index(fields=['person', 'effective_start_date'], name='hr_organiza_person__45c6d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmanager',
            constraint=models.UniqueConstraint(fields=('organization', 'person', 'effective_start_date'), name='unique_org_manager_assignment'),
        ),
        migrations.AddConstraint(
            model_name='organizationmanager',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end_date__isnull', True), ('effective_end_date__gte', models.F('effective_start_date')), _connector='OR'), name='org_manager_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='positionqualificationrequirement',
            index=models.Index(fields=['position'], name='hr_position_positio_88f31e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='positionqualificationrequirement',
            unique_together={('position', 'qualification_type', 'qualification_title')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organization', 'effective_start_date', 'effective_end_date'], name='hr_position_organiz_f7e810_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['code'], name='hr_position_code_878671_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organization', 'job'], name='hr_position_organiz_15d1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['position_status'], name='hr_position_positio_cbaa7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('code', 'organization', 'effective_start_date'), name='unique_position_code_org_start_date'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('full_time_equivalent__gte', 0.1), ('full_time_equivalent__lte', 1.5)), name='position_fte_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('head_count__gt', 0)), name='position_headcount_positive'),
        ),
    ]
