# Generated by Django 5.2.8 on 2026-01-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graderatetype',
            options={'ordering': ['code'], 'verbose_name': 'Grade Rate Type', 'verbose_name_plural': 'Grade Rate Types'},
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_active_grade_code_per_org',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='hr_grade_code_6c2209_idx',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='code',
        ),
        migrations.RemoveField(
            model_name='graderatetype',
            name='has_range',
        ),
        migrations.RemoveField(
            model_name='graderatetype',
            name='name',
        ),
    ]
