# Generated by Django 5.2.8 on 2026-01-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_structures', '0002_alter_graderatetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='business_group',
            field=models.ForeignKey(blank=True, help_text='Root organization (Business Group) that owns this location', limit_choices_to={'business_group__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='work_structures.organization'),
        ),
    ]
