# Generated by Django 5.2.8 on 2026-01-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_structures', '0003_alter_location_business_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Effective from date', null=True),
        ),
    ]
