# Generated by Django 5.2.8 on 2026-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_structures', '0004_alter_grade_effective_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Effective from date', null=True),
        ),
    ]
