# Generated by Django 5.2.8 on 2026-01-23 10:03

import django.db.models.deletion
from django.db import migrations, models


def migrate_currencies(apps, schema_editor):
    GradeRate = apps.get_model('work_structures', 'GradeRate')
    LookupType = apps.get_model('lookups', 'LookupType')
    LookupValue = apps.get_model('lookups', 'LookupValue')

    # Get or create Currency lookup type
    # We use 'Currency' as the name based on previous context
    currency_type, _ = LookupType.objects.get_or_create(
        name='Currency',
        defaults={'description': 'Currency codes'}
    )

    for rate in GradeRate.objects.all():
        if rate.currency_old:
            # Create or get the lookup value for the currency string
            # We strip whitespace just in case
            currency_code = str(rate.currency_old).strip()
            if currency_code:
                currency_val, _ = LookupValue.objects.get_or_create(
                    lookup_type=currency_type,
                    name=currency_code,
                    defaults={'is_active': True}
                )
                rate.currency = currency_val
                rate.save()


def reverse_migrate_currencies(apps, schema_editor):
    GradeRate = apps.get_model('work_structures', 'GradeRate')
    for rate in GradeRate.objects.all():
        if rate.currency:
            rate.currency_old = rate.currency.name
            rate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('work_structures', '0005_alter_location_effective_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graderate',
            old_name='currency',
            new_name='currency_old',
        ),
        migrations.AddField(
            model_name='graderate',
            name='currency',
            field=models.ForeignKey(
                help_text='Currency lookup value',
                limit_choices_to={'is_active': True, 'lookup_type__name': 'Currency'},
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='grade_rates',
                to='lookups.lookupvalue'
            ),
        ),
        migrations.RunPython(migrate_currencies, reverse_code=reverse_migrate_currencies),
        migrations.RemoveField(
            model_name='graderate',
            name='currency_old',
        ),
    ]
