# Generated by Django 5.2.8 on 2026-01-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('work_structures', '0006_alter_graderate_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderate',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency lookup value', limit_choices_to={'is_active': True, 'lookup_type__name': 'Currency'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_rates', to='lookups.lookupvalue'),
        ),
    ]
