# Generated by Django 5.2.8 on 2026-01-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_structures', '0007_alter_graderate_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobqualificationrequirement',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='positionqualificationrequirement',
            name='is_mandatory',
        ),
    ]
