# Generated by Django 5.2.8 on 2026-01-28 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('work_structures', '0008_remove_jobqualificationrequirement_is_mandatory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('organization', 'grade_name'), name='unique_grade_name_per_org'),
        ),
    ]
