# Generated by Django 5.2.8 on 2025-12-23 05:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('finance_businesspartner', '0001_initial'),
        ('po', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated GRN number', max_length=50, unique=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, help_text='Date when goods were received')),
                ('expected_date', models.DateField(blank=True, help_text='Expected delivery date from PO', null=True)),
                ('grn_type', models.CharField(choices=[('Catalog', 'Catalog'), ('Non-Catalog', 'Non-Catalog'), ('Service', 'Service')], help_text='Type of goods receipt (matches PO type)', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total amount of goods received (calculated from lines)', max_digits=14)),
                ('notes', models.TextField(blank=True, help_text='General notes about this receipt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('po_header', models.ForeignKey(help_text='Purchase Order being received', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='po.poheader')),
                ('received_by', models.ForeignKey(help_text='Person who received the goods', on_delete=django.db.models.deletion.PROTECT, related_name='received_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier delivering the goods', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='finance_businesspartner.supplier')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'ordering': ['-receipt_date', '-grn_number'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence number')),
                ('item_name', models.CharField(help_text='Item name', max_length=255)),
                ('item_description', models.TextField(blank=True, help_text='Item description')),
                ('quantity_ordered', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity ordered in PO (0 for gifts)', max_digits=14)),
                ('quantity_received', models.DecimalField(decimal_places=3, help_text='Quantity actually received', max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per unit (from PO or entered)', max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Line total (quantity_received * unit_price)', max_digits=14)),
                ('is_gift', models.BooleanField(default=False, help_text='True if this is a gift/bonus item not in the original PO')),
                ('line_notes', models.TextField(blank=True, help_text='Notes about this line item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods_receipt', models.ForeignKey(help_text='Parent Goods Receipt', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receiving.goodsreceipt')),
                ('po_line_item', models.ForeignKey(blank=True, help_text='Source PO line item (null for gifts/extras)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='po.polineitem')),
                ('unit_of_measure', models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Goods Receipt Line',
                'verbose_name_plural': 'Goods Receipt Lines',
                'ordering': ['goods_receipt', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['supplier', 'receipt_date'], name='receiving_g_supplie_5d9758_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['po_header'], name='receiving_g_po_head_f20089_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptline',
            index=models.Index(fields=['goods_receipt', 'line_number'], name='receiving_g_goods_r_596f27_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptline',
            index=models.Index(fields=['po_line_item'], name='receiving_g_po_line_bc4532_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceiptline',
            unique_together={('goods_receipt', 'line_number')},
        ),
    ]
