# Generated by Django 5.2.8 on 2026-01-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='receiving_type',
            field=models.CharField(choices=[('PARTIAL', 'Partial Receiving'), ('FULLY', 'Fully Receiving')], default='PARTIAL', help_text='Type of receiving: PARTIAL (any quantity ≤ ordered) or FULLY (validates against tolerance)', max_length=10),
        ),
    ]
