# Generated by Django 5.2.8 on 2026-01-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_goodsreceiptline_receiving_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='budget_actual_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when budget actual was updated', null=True),
        ),
    ]
