# Generated by Django 5.2.8 on 2025-12-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_SegmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(help_text="Display name (e.g., 'Entity', 'Account', 'Project')", max_length=50, unique=True)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this segment is required in transactions')),
                ('has_hierarchy', models.BooleanField(default=False, help_text='Whether this segment supports parent-child relationships')),
                ('length', models.IntegerField(default=50, help_text='Fixed code length for this segment (all codes must be this length)')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying in UI (lower = first)')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this segment represents', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment Type',
                'verbose_name_plural': 'Segment Types',
                'db_table': 'XX_SEGMENT_TYPE_XX',
                'ordering': ['display_order', 'segment_name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField()),
                ('JournalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GeneralLedger', to='finance_gl.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='XX_Segment_combination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Optional description of this envelope', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this envelope is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment Combination',
                'verbose_name_plural': 'Segment Combinations',
                'db_table': 'XX_SEGMENT_combination_XX',
                'indexes': [models.Index(fields=['is_active'], name='XX_SEGMENT__is_acti_a29ef9_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=14)),
                ('type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=16)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance_gl.journalentry')),
                ('segment_combination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_gl.xx_segment_combination')),
            ],
        ),
        migrations.CreateModel(
            name='XX_Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The actual segment code/value', max_length=50)),
                ('parent_code', models.CharField(blank=True, help_text='Parent segment code for hierarchical segments', max_length=50, null=True)),
                ('alias', models.CharField(blank=True, help_text='Display name / description', max_length=255, null=True)),
                ('node_type', models.CharField(choices=[('parent', 'Parent'), ('sub_parent', 'Sub-Parent'), ('child', 'Child')], help_text='Node type in hierarchy: parent (root), sub_parent (intermediate), or child (leaf)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment value is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_type', models.ForeignKey(help_text='Which segment type this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='finance_gl.xx_segmenttype')),
            ],
            options={
                'verbose_name': 'Segment Value',
                'verbose_name_plural': 'Segment Values',
                'db_table': 'XX_SEGMENT_XX',
            },
        ),
        migrations.CreateModel(
            name='segment_combination_detials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.ForeignKey(help_text='The actual segment code/value', on_delete=django.db.models.deletion.CASCADE, to='finance_gl.xx_segment')),
                ('segment_combination', models.ForeignKey(help_text='Parent segment combination', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance_gl.xx_segment_combination')),
                ('segment_type', models.ForeignKey(help_text='Which segment type this value belongs to', on_delete=django.db.models.deletion.CASCADE, to='finance_gl.xx_segmenttype')),
            ],
            options={
                'verbose_name': 'Segment Combination Detail',
                'verbose_name_plural': 'Segment Combination Details',
                'db_table': 'segment_combination_detials_XX',
            },
        ),
        migrations.AddIndex(
            model_name='xx_segment',
            index=models.Index(fields=['segment_type', 'code'], name='XX_SEGMENT__segment_74fd90_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_segment',
            index=models.Index(fields=['segment_type', 'parent_code'], name='XX_SEGMENT__segment_05aa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_segment',
            index=models.Index(fields=['code'], name='XX_SEGMENT__code_fd0bec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xx_segment',
            unique_together={('segment_type', 'code')},
        ),
        migrations.AddIndex(
            model_name='segment_combination_detials',
            index=models.Index(fields=['segment_combination', 'segment_type'], name='segment_com_segment_bf8693_idx'),
        ),
        migrations.AddIndex(
            model_name='segment_combination_detials',
            index=models.Index(fields=['segment_type', 'segment'], name='segment_com_segment_9c1e18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='segment_combination_detials',
            unique_together={('segment_combination', 'segment_type')},
        ),
    ]
