# Generated by Django 5.2.8 on 2025-12-19 12:20

import django.db.models.deletion
import hr.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='hr_enterpri_code_2be6c9_idx'), models.Index(fields=['status'], name='hr_enterpri_status_4bb5cd_idx')],
            },
            bases=(hr.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_groups', to='hr.enterprise')),
            ],
            options={
                'verbose_name': 'Business Group',
                'verbose_name_plural': 'Business Groups',
                'ordering': ['enterprise', 'name'],
            },
            bases=(hr.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.businessgroup')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
            bases=(hr.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GradeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='hr.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='hr.businessgroup')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='hr.enterprise')),
            ],
            bases=(hr.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='hr.businessgroup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hr.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='hr.location')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
            bases=(hr.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.grade')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.location')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='hr.position')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['code', '-effective_start_date'],
            },
            bases=(hr.models.base.CodeGenerationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserDataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='If true, user can access ALL Business Groups')),
                ('business_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.businessgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_data_scopes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='hr.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Manager',
                'verbose_name_plural': 'Department Managers',
                'constraints': [models.UniqueConstraint(fields=('department', 'manager', 'effective_start_date'), name='unique_dept_manager_assignment')],
            },
        ),
        migrations.AddIndex(
            model_name='businessgroup',
            index=models.Index(fields=['enterprise', 'code'], name='hr_business_enterpr_97c2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='businessgroup',
            index=models.Index(fields=['status'], name='hr_business_status_ff918f_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessgroup',
            constraint=models.UniqueConstraint(fields=('enterprise', 'code'), name='unique_bg_code_per_enterprise'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', 'effective_start_date'], name='hr_departme_code_60d055_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['business_group', 'status'], name='hr_departme_busines_776ff9_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('business_group', 'code', 'effective_start_date'), name='unique_dept_version'),
        ),
        migrations.AddConstraint(
            model_name='userdatascope',
            constraint=models.UniqueConstraint(fields=('user', 'business_group'), name='unique_user_bg_scope'),
        ),
    ]
