# Generated by Django 5.2.8 on 2025-12-17 12:22

from django.db import migrations

def register_pages(apps, schema_editor):
    try:
        Page = apps.get_model('job_roles', 'Page')
    except LookupError:
        # Fallback if app label is core.job_roles or different
        try:
             Page = apps.get_model('core.job_roles', 'Page')
        except LookupError:
             return # Cannot find Page model

    pages = [
        {'name': 'hr_enterprise', 'display_name': 'Enterprise Management', 'description': 'Manage enterprise details'},
        {'name': 'hr_business_group', 'display_name': 'Business Group Management', 'description': 'Manage business groups'},
        {'name': 'hr_location', 'display_name': 'Location Management', 'description': 'Manage physical locations'},
        {'name': 'hr_department', 'display_name': 'Department Management', 'description': 'Manage departments'},
        {'name': 'hr_position', 'display_name': 'Position Management', 'description': 'Manage positions'},
        {'name': 'hr_grade', 'display_name': 'Grade Management', 'description': 'Manage grades and rates'},
    ]
    for p in pages:
        Page.objects.get_or_create(name=p['name'], defaults=p)

def remove_pages(apps, schema_editor):
    try:
        Page = apps.get_model('job_roles', 'Page')
    except LookupError:
        try:
             Page = apps.get_model('core.job_roles', 'Page')
        except LookupError:
             return

    names = ['hr_enterprise', 'hr_business_group', 'hr_location', 'hr_department', 'hr_position', 'hr_grade']
    Page.objects.filter(name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('job_roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(register_pages, remove_pages),
    ]
