# Generated by Django 6.0 on 2025-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When payment was approved', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When payment was rejected', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, help_text='When payment was submitted for approval', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval workflow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection'),
        ),
    ]
