# Generated by Django 5.2.8 on 2025-12-12 17:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0003_invoice_approved_at_invoice_rejected_at_and_more'),
        ('payments', '0002_payment_approved_at_payment_rejected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be paid across all installments', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the payment plan terms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='The invoice this payment plan is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='finance_invoice.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment Plan',
                'verbose_name_plural': 'Invoice Payment Plans',
                'db_table': 'invoice_payment_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='Sequential number of this installment (1, 2, 3, etc.)')),
                ('due_date', models.DateField(db_index=True, help_text='Date when this installment payment is due')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid for this installment', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount that has been paid so far', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description for this installment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_plan', models.ForeignKey(help_text='The payment plan this installment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.invoicepaymentplan')),
            ],
            options={
                'verbose_name': 'Payment Plan Installment',
                'verbose_name_plural': 'Payment Plan Installments',
                'db_table': 'payment_plan_installment',
                'ordering': ['payment_plan', 'installment_number'],
                'unique_together': {('payment_plan', 'installment_number')},
            },
        ),
    ]
