# Generated by Django 5.2.8 on 2026-01-06 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0001_initial'),
        ('payments', '0003_invoicepaymentplan_paymentplaninstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account used for this payment (for cash management reconciliation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cash_management.bankaccount'),
        ),
    ]
