# Generated by Django 5.2.8 on 2026-01-09 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0002_bankaccount_transction_type_bankstatement_and_more'),
        ('payments', '0004_payment_bank_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Payment method (Cash, Check, Wire Transfer, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cash_management.paymenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment (Outgoing)'), ('RECEIPT', 'Receipt (Incoming)')], default='PAYMENT', help_text='Payment direction: PAYMENT (outgoing) or RECEIPT (incoming)', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, help_text='User who reconciled this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciled_date',
            field=models.DateTimeField(blank=True, help_text='When payment was reconciled with bank statement', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_status',
            field=models.CharField(choices=[('UNRECONCILED', 'Unreconciled'), ('RECONCILED', 'Reconciled')], default='UNRECONCILED', help_text='Bank reconciliation status', max_length=20),
        ),
    ]
