# Generated by Django 4.2.7 on 2025-12-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate_to_base_currency',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Percent (e.g. 5 = 5%)', max_digits=6)),
                ('category', models.CharField(choices=[('STANDARD', 'Standard'), ('ZERO', 'Zero Rated'), ('EXEMPT', 'Exempt'), ('RC', 'Reverse Charge')], default='STANDARD', max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='Is this rate currently active?')),
                ('country', models.ForeignKey(default='AE', on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='finance_core.country')),
            ],
            options={
                'ordering': ['country', 'category'],
                'indexes': [models.Index(fields=['country', 'category'], name='finance_cor_country_363dfb_idx')],
                'unique_together': {('country', 'category')},
            },
        ),
    ]
