# Generated by Django 6.0 on 2025-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core', '0002_country_currency_exchange_rate_to_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Percent (e.g. 5 = 5%)', max_digits=6),
        ),
    ]
