# Generated by Django 5.2.8 on 2025-12-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core', '0003_alter_taxrate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
