# Generated by Django 5.2.8 on 2025-12-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_alter_approvalworkflowstagetemplate_required_role'),
        ('job_roles', '0001_initial'),
        ('user_accounts', '0002_role_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': 'User Type', 'verbose_name_plural': 'User Types'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_role',
            field=models.ForeignKey(blank=True, help_text='Job role determines page access permissions', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='job_roles.jobrole'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type_name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
