# Generated by Django 5.2.8 on 2026-01-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_useraccount_created_at_useraccount_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
    ]
