# Generated by Django 5.2.8 on 2025-12-12 09:23

from django.db import migrations, models


def convert_null_to_empty_string(apps, schema_editor):
    """Convert NULL description values to empty strings before schema change."""
    UserType = apps.get_model('user_accounts', 'UserType')
    UserType.objects.filter(description__isnull=True).update(description='')


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_remove_customuser_role_alter_customuser_options_and_more'),
    ]

    operations = [
        # First, convert existing NULL values to empty strings
        migrations.RunPython(
            convert_null_to_empty_string,
            reverse_code=migrations.RunPython.noop,
        ),
        # Then, alter the field to remove null=True
        migrations.AlterField(
            model_name='usertype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
