# Generated by Django 5.2.8 on 2026-01-05 14:28

import Finance.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_core', '0004_alter_country_code'),
        ('finance_gl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Official name of the bank', max_length=255, unique=True)),
                ('bank_code', models.CharField(help_text='Unique bank identification code', max_length=50, unique=True)),
                ('address', models.TextField(blank=True, help_text='Headquarters address')),
                ('phone', models.CharField(blank=True, help_text='Main contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Main contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Bank website URL')),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=11)),
                ('routing_number', models.CharField(blank=True, help_text='Routing number (country-specific)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bank is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the bank')),
                ('country', models.ForeignKey(help_text='Country where bank is headquartered', on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='finance_core.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banks_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banks_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['bank_name'],
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='Name of the branch (e.g., Downtown Branch, Airport Branch)', max_length=255)),
                ('branch_code', models.CharField(help_text='Unique branch code within the bank', max_length=50)),
                ('address', models.TextField(help_text='Branch physical address')),
                ('city', models.CharField(blank=True, help_text='City where branch is located', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Branch phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Branch email', max_length=254)),
                ('manager_name', models.CharField(blank=True, help_text='Name of branch manager', max_length=255)),
                ('manager_phone', models.CharField(blank=True, help_text='Branch manager phone', max_length=50)),
                ('swift_code', models.CharField(blank=True, help_text='Branch-specific SWIFT code (if different from main bank)', max_length=11)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC code (for Indian banks)', max_length=20)),
                ('routing_number', models.CharField(blank=True, help_text='Branch routing number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branch is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the branch')),
                ('bank', models.ForeignKey(help_text='Parent bank for this branch', on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='cash_management.bank')),
                ('country', models.ForeignKey(help_text='Country where branch is located', on_delete=django.db.models.deletion.PROTECT, related_name='bank_branches', to='finance_core.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_branches_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_branches_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Branch',
                'verbose_name_plural': 'Bank Branches',
                'ordering': ['bank', 'branch_name'],
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Bank account number', max_length=50, unique=True)),
                ('account_name', models.CharField(help_text='Name on the account', max_length=255)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current Account'), ('SAVINGS', 'Savings Account'), ('FIXED_DEPOSIT', 'Fixed Deposit'), ('LOAN', 'Loan Account'), ('OVERDRAFT', 'Overdraft Account')], default='CURRENT', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance when account was created', max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance of the account', max_digits=14)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=34)),
                ('opening_date', models.DateField(blank=True, help_text='Date when account was opened', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes or description')),
                ('cash_GL_combination', models.ForeignKey(help_text='GL segment combination for this bank account', on_delete=django.db.models.deletion.PROTECT, related_name='cash_accounts', to='finance_gl.xx_segment_combination')),
                ('cash_clearing_GL_combination', models.ForeignKey(help_text='GL segment combination for cash clearing account', on_delete=django.db.models.deletion.PROTECT, related_name='cash_clearing_accounts', to='finance_gl.xx_segment_combination')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency of this account', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='finance_core.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_updated', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(help_text='Bank branch where account is held', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='cash_management.bankbranch')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['branch__bank', 'account_number'],
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['bank_code'], name='cash_manage_bank_co_8e4d72_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['country'], name='cash_manage_country_094cca_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['is_active'], name='cash_manage_is_acti_6e8c36_idx'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['bank', 'branch_code'], name='cash_manage_bank_id_781fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['country'], name='cash_manage_country_81c3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['is_active'], name='cash_manage_is_acti_2878ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankbranch',
            unique_together={('bank', 'branch_code')},
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_number'], name='cash_manage_account_8b5542_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['branch'], name='cash_manage_branch__618cff_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_type'], name='cash_manage_account_1262ad_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active'], name='cash_manage_is_acti_673b4d_idx'),
        ),
    ]
