# Generated by Django 5.2.8 on 2026-01-09 05:04

import Finance.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0001_initial'),
        ('payments', '0004_payment_bank_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='transction_type',
            field=models.CharField(choices=[('bank transfer', 'bank transfer'), ('check', 'check'), ('online payment', 'online payment')], default='bank transfer', help_text='Type of transactions allowed for this account', max_length=50),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(help_text='Bank statement reference number', max_length=100)),
                ('statement_date', models.DateField(help_text='Date of the bank statement')),
                ('from_date', models.DateField(help_text='Statement period start date')),
                ('to_date', models.DateField(help_text='Statement period end date')),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Opening balance at period start', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='Closing balance at period end', max_digits=14)),
                ('transaction_count', models.IntegerField(default=0, help_text='Number of transactions in this statement')),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, help_text='Total debit amount', max_digits=14)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, help_text='Total credit amount', max_digits=14)),
                ('reconciliation_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved')], default='PENDING', help_text='Reconciliation status', max_length=20)),
                ('import_file_name', models.CharField(blank=True, default='', help_text='Original import file name', max_length=255)),
                ('import_date', models.DateTimeField(blank=True, help_text='When statement was imported', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(help_text='Bank account for this statement', on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='cash_management.bankaccount')),
                ('created_by', models.ForeignKey(help_text='User who created this statement', on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_statements', to=settings.AUTH_USER_MODEL)),
                ('imported_by', models.ForeignKey(blank=True, help_text='User who imported this statement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_statements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this statement', on_delete=django.db.models.deletion.PROTECT, related_name='updated_bank_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-statement_date', '-created_at'],
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(help_text='Line number in the statement')),
                ('transaction_date', models.DateField(help_text='Date transaction was initiated')),
                ('value_date', models.DateField(help_text='Date transaction was valued/cleared')),
                ('description', models.TextField(blank=True, default='', help_text='Transaction description from bank')),
                ('reference_number', models.CharField(blank=True, default='', help_text='Bank reference or transaction ID', max_length=100)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount (if applicable)', max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount (if applicable)', max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Balance after this transaction', max_digits=14)),
                ('reconciliation_status', models.CharField(choices=[('UNRECONCILED', 'Unreconciled'), ('RECONCILED', 'Reconciled'), ('DISCREPANCY', 'Discrepancy')], default='UNRECONCILED', help_text='Reconciliation status of this line', max_length=20)),
                ('reconciled_date', models.DateTimeField(blank=True, help_text='When this line was reconciled', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_statement', models.ForeignKey(help_text='Bank statement this line belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='cash_management.bankstatement')),
                ('created_by', models.ForeignKey(help_text='User who created/imported this line', on_delete=django.db.models.deletion.PROTECT, related_name='created_statement_lines', to=settings.AUTH_USER_MODEL)),
                ('matched_payment', models.ForeignKey(blank=True, help_text='System payment matched to this statement line', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_statement_lines', to='payments.payment')),
                ('reconciled_by', models.ForeignKey(blank=True, help_text='User who reconciled this line', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_statement_lines', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this line', on_delete=django.db.models.deletion.PROTECT, related_name='updated_statement_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement Line',
                'verbose_name_plural': 'Bank Statement Lines',
                'ordering': ['bank_statement', 'line_number'],
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankStatementLineMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('PARTIAL', 'Partial Match'), ('UNMATCHED', 'Unmatched'), ('MANUAL', 'Manual Match')], default='MATCHED', help_text='Match status', max_length=20)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact Match'), ('AMOUNT_DATE', 'Amount and Date'), ('REFERENCE', 'Reference Number'), ('DESCRIPTION', 'Description Match'), ('MANUAL', 'Manual')], help_text='How the match was determined', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Match confidence percentage (0-100)', max_digits=5)),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount difference between statement line and transaction', max_digits=14)),
                ('matched_at', models.DateTimeField(auto_now_add=True, help_text='When match was created')),
                ('notes', models.TextField(blank=True, default='', help_text='Match notes or explanation')),
                ('matched_by', models.ForeignKey(help_text='User who created this match', on_delete=django.db.models.deletion.PROTECT, related_name='created_statement_matches', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='System payment transaction', on_delete=django.db.models.deletion.PROTECT, related_name='statement_matches', to='payments.payment')),
                ('statement_line', models.ForeignKey(help_text='Bank statement line from import', on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='cash_management.bankstatementline')),
            ],
            options={
                'verbose_name': 'Bank Statement Line Match',
                'verbose_name_plural': 'Bank Statement Line Matches',
                'ordering': ['-matched_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_code', models.CharField(help_text='Unique code for the payment method (e.g., CASH, CHECK, WIRE)', max_length=20, unique=True)),
                ('payment_method_name', models.CharField(help_text='Display name for the payment method', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the payment method')),
                ('enable_reconcile', models.BooleanField(default=True, help_text='Whether payments using this method should be reconciled with bank statements')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_types', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_payment_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
                'ordering': ['payment_method_name'],
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account', 'statement_date'], name='cash_manage_bank_ac_2aabb0_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['reconciliation_status'], name='cash_manage_reconci_53d88f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['from_date', 'to_date'], name='cash_manage_from_da_8e216f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatement',
            unique_together={('bank_account', 'statement_number')},
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['bank_statement', 'line_number'], name='cash_manage_bank_st_d00441_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['transaction_date'], name='cash_manage_transac_e10457_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['reconciliation_status'], name='cash_manage_reconci_db3837_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['reference_number'], name='cash_manage_referen_5a5558_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatementline',
            unique_together={('bank_statement', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='bankstatementlinematch',
            index=models.Index(fields=['statement_line'], name='cash_manage_stateme_0a8592_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementlinematch',
            index=models.Index(fields=['payment'], name='cash_manage_payment_29e3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementlinematch',
            index=models.Index(fields=['match_status'], name='cash_manage_match_s_347da8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttype',
            index=models.Index(fields=['payment_method_code'], name='cash_manage_payment_4c4b49_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttype',
            index=models.Index(fields=['is_active'], name='cash_manage_is_acti_d0d943_idx'),
        ),
    ]
