# Generated by Django 5.2.8 on 2025-12-23 03:27

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PR', '0002_pritem_conversion_date_pritem_converted_to_po_and_more'),
        ('catalog', '0001_initial'),
        ('finance_businesspartner', '0001_initial'),
        ('finance_core', '0004_alter_country_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('po_date', models.DateField(default=datetime.date.today)),
                ('po_type', models.CharField(choices=[('Catalog', 'Catalog'), ('Non-Catalog', 'Non-Catalog'), ('Service', 'Service')], default='Catalog', help_text='Type of PO: Catalog, Non-Catalog, or Service', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed/Sent to Vendor'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('receiving_date', models.DateField(blank=True, null=True)),
                ('receiving_address', models.TextField(blank=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=200)),
                ('receiver_contact', models.CharField(blank=True, max_length=200)),
                ('receiver_phone', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal in transaction currency', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax in transaction currency', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total in transaction currency', max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_approved', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_cancelled', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Transaction currency', on_delete=django.db.models.deletion.PROTECT, to='finance_core.currency')),
                ('source_pr_headers', models.ManyToManyField(blank=True, help_text='Source PR Headers that contribute to this PO', related_name='converted_pos', to='PR.pr')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier_name', models.ForeignKey(help_text='Vendor/Supplier', on_delete=django.db.models.deletion.PROTECT, to='finance_businesspartner.businesspartner')),
            ],
            options={
                'db_table': 'po_header',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='Line sequence number within PO')),
                ('line_type', models.CharField(choices=[('Catalog', 'Catalog'), ('Non-Catalog', 'Non-Catalog'), ('Service', 'Service')], help_text='Type of line item (must match PO header type)', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Ordered quantity', max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: quantity × unit_price', max_digits=15)),
                ('item_name', models.CharField(help_text='Item name', max_length=255)),
                ('item_description', models.TextField(help_text='Detailed item description')),
                ('quantity_from_pr', models.DecimalField(blank=True, decimal_places=3, help_text='Original quantity from PR', max_digits=15, null=True)),
                ('price_from_pr', models.DecimalField(blank=True, decimal_places=2, help_text='Original estimated price from PR', max_digits=15, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity received so far', max_digits=15)),
                ('line_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_header', models.ForeignKey(help_text='Parent PO Header', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='po.poheader')),
                ('source_pr_item', models.ForeignKey(blank=True, help_text='Source PR line item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_po_lines', to='PR.pritem')),
                ('unit_of_measure', models.ForeignKey(help_text='Unit of measure', on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure')),
            ],
            options={
                'db_table': 'po_line_item',
                'ordering': ['po_header', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['po_number'], name='po_header_po_numb_aedc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['status'], name='po_header_status_54389f_idx'),
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['po_type'], name='po_header_po_type_562bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='poheader',
            index=models.Index(fields=['supplier_name'], name='po_header_supplie_2acab3_idx'),
        ),
        migrations.AddIndex(
            model_name='polineitem',
            index=models.Index(fields=['po_header', 'line_number'], name='po_line_ite_po_head_8f7f50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polineitem',
            unique_together={('po_header', 'line_number')},
        ),
    ]
