# Generated by Django 5.2.8 on 2026-01-13 23:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core', '0004_alter_country_code'),
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='delivery_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery charges in transaction currency', max_digits=15),
        ),
        migrations.AddField(
            model_name='poheader',
            name='tax_rate',
            field=models.ForeignKey(blank=True, help_text='Tax rate applicable to this PO', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance_core.taxrate'),
        ),
    ]
