# Generated by Django 5.2.8 on 2026-01-14 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_poheader_delivery_amount_poheader_tax_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type or file extension', max_length=100)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_data', models.BinaryField(help_text='Binary file data (BLOB)')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment')),
                ('po_header', models.ForeignKey(help_text='Parent PO Header', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='po.poheader')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'po_attachment',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['po_header', '-upload_date'], name='po_attachme_po_head_773022_idx')],
            },
        ),
    ]
