# Generated by Django 5.2.8 on 2026-01-15 00:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_poattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='polineitem',
            name='tolerance_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage tolerance for over/under receiving (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
