# Generated by Django 5.2.8 on 2026-01-22 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_gl', '0001_initial'),
        ('po', '0004_polineitem_tolerance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='budget_encumbered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when budget encumbrance was created', null=True),
        ),
        migrations.AddField(
            model_name='poheader',
            name='budget_pr_commitment_released',
            field=models.BooleanField(default=False, help_text='Tracks if source PR commitment was released during PO approval'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='segment_combination',
            field=models.ForeignKey(blank=True, help_text='GL account coding inherited from PR or assigned directly', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='finance_gl.xx_segment_combination'),
        ),
    ]
