# Generated by Django 5.2.8 on 2026-01-21 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('person', '0001_initial'),
        ('work_structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_position',
            field=models.ForeignKey(blank=True, help_text='Position applied for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_structures.position'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicant',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_action_reason',
            field=models.ForeignKey(help_text='Reason for assignment action (e.g., Hire, Promotion)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Assignment Action Reason'}, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_by_action_reason', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_status',
            field=models.ForeignKey(help_text='Status of the assignment (e.g., Active, Suspended)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Assignment Status'}, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_by_status', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='business_group',
            field=models.ForeignKey(help_text='Root organization (Business Group)', limit_choices_to={'business_group__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='bg_assignments', to='work_structures.organization'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.ForeignKey(help_text="Department (Organization where name='department')", on_delete=django.db.models.deletion.PROTECT, related_name='dept_assignments', to='work_structures.organization'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.ForeignKey(help_text='Grade level of the assignment', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='work_structures.grade'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='job',
            field=models.ForeignKey(help_text='Job assigned to the person', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='work_structures.job'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='payroll',
            field=models.ForeignKey(blank=True, help_text='Payroll associated with the assignment', limit_choices_to={'is_active': True, 'lookup_type__name': 'Payroll'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_by_payroll', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='position',
            field=models.ForeignKey(help_text='Position assigned to the person', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='work_structures.position'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='probation_period',
            field=models.ForeignKey(blank=True, help_text='Probation period duration (e.g., 3 months)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Probation Period'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_by_probation_period', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='salary_basis',
            field=models.ForeignKey(blank=True, help_text='Salary basis for the assignment', limit_choices_to={'is_active': True, 'lookup_type__name': 'Salary Basis'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_by_salary_basis', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='termination_notice_period',
            field=models.ForeignKey(blank=True, help_text='Notice period required for termination', limit_choices_to={'is_active': True, 'lookup_type__name': 'Termination Notice Period'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_by_notice_period', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competency',
            name='category',
            field=models.ForeignKey(help_text='Competency category from lookup (e.g., Technical, Behavioral)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Competency Category'}, on_delete=django.db.models.deletion.PROTECT, related_name='competencies_by_category', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='competency',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competency',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='competency',
            field=models.ForeignKey(help_text='Competency being assessed', on_delete=django.db.models.deletion.PROTECT, related_name='proficiencies', to='person.competency'),
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='proficiency_level',
            field=models.ForeignKey(help_text='Proficiency level (e.g., Beginner, Intermediate, Expert)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Proficiency Level'}, on_delete=django.db.models.deletion.PROTECT, related_name='proficiencies_by_level', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='proficiency_source',
            field=models.ForeignKey(help_text='How proficiency was assessed (e.g., Self-Assessment, Manager Assessment)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Proficiency Source'}, on_delete=django.db.models.deletion.PROTECT, related_name='proficiencies_by_source', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='assignment_role',
            field=models.ForeignKey(blank=True, help_text='Role/position for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_structures.position'),
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='current_assignment',
            field=models.ForeignKey(blank=True, help_text='Current organization/department/team assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_structures.organization'),
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_end_reason',
            field=models.ForeignKey(blank=True, help_text='Reason for contract ending (optional)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Contract End Reason'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_end_reason_records', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_status',
            field=models.ForeignKey(help_text='Current status of the contract (e.g., Active, Ended)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Contract Status'}, on_delete=django.db.models.deletion.PROTECT, related_name='contract_status_records', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Contract associated with this assignment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='person.contract'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='emergency_for_employee',
            field=models.ForeignKey(blank=True, help_text='Employee this is an emergency contact for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='person.employee'),
        ),
        migrations.AddField(
            model_name='jobcompetencyrequirement',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='person.competency'),
        ),
        migrations.AddField(
            model_name='jobcompetencyrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcompetencyrequirement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_requirements', to='work_structures.job'),
        ),
        migrations.AddField(
            model_name='jobcompetencyrequirement',
            name='proficiency_level',
            field=models.ForeignKey(help_text='Required proficiency level for this competency', limit_choices_to={'is_active': True, 'lookup_type__name': 'Proficiency Level'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='jobcompetencyrequirement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_periods', to='person.person'),
        ),
        migrations.AddField(
            model_name='contract',
            name='person',
            field=models.ForeignKey(help_text='Person associated with this contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='person.person'),
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contingent_worker_periods', to='person.person'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_periods', to='person.person'),
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='person',
            field=models.ForeignKey(help_text='Person who has this competency', on_delete=django.db.models.deletion.PROTECT, related_name='competency_proficiencies', to='person.person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='line_manager',
            field=models.ForeignKey(blank=True, help_text='Line manager for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assignments', to='person.person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(help_text='Person associated with this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='person.person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Project manager for this assignment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_managed_assignments', to='person.person'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_periods', to='person.person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(help_text='Person this address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='person.person'),
        ),
        migrations.AddField(
            model_name='persontype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persontype',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(help_text='Employee subtype (Permanent, Temporary, etc.)', limit_choices_to={'base_type': 'EMP', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='person.persontype'),
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='worker_type',
            field=models.ForeignKey(help_text='Worker subtype (Consultant, Contractor, etc.)', limit_choices_to={'base_type': 'CWK', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='person.persontype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(help_text='Contact subtype (Vendor, Emergency, Customer, etc.)', limit_choices_to={'base_type': 'CON', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='person.persontype'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_type',
            field=models.ForeignKey(help_text='Applicant subtype (Internal, External, etc.)', limit_choices_to={'base_type': 'APL', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='person.persontype'),
        ),
        migrations.AddField(
            model_name='persontypedffconfig',
            name='person_type',
            field=models.ForeignKey(help_text='Which person type this field applies to', on_delete=django.db.models.deletion.CASCADE, related_name='dff_fields', to='person.persontype'),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_requirements', to='person.competency'),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_requirements', to='work_structures.position'),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='proficiency_level',
            field=models.ForeignKey(help_text='Required proficiency level for this competency', limit_choices_to={'is_active': True, 'lookup_type__name': 'Proficiency Level'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualification',
            name='awarding_entity',
            field=models.ForeignKey(help_text='University or institution that awarded the qualification', limit_choices_to={'is_active': True, 'lookup_type__name': 'Awarding Entity'}, on_delete=django.db.models.deletion.PROTECT, related_name='qualifications_by_entity', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='competency_achieved',
            field=models.ManyToManyField(blank=True, help_text='Competencies gained from this qualification', related_name='qualifications', to='person.competency'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualification',
            name='person',
            field=models.ForeignKey(help_text='Person who has this qualification', on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='person.person'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_status',
            field=models.ForeignKey(help_text='Status (e.g., Completed, In Progress)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Qualification Status'}, on_delete=django.db.models.deletion.PROTECT, related_name='qualifications_by_status', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_title',
            field=models.ForeignKey(help_text='Specific qualification title (e.g., Computer Science, MBA)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Qualification Title'}, on_delete=django.db.models.deletion.PROTECT, related_name='qualifications_by_title', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_type',
            field=models.ForeignKey(help_text='Type of qualification (e.g., Bachelor, Master, Certification)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Qualification Type'}, on_delete=django.db.models.deletion.PROTECT, related_name='qualifications_by_type', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='tuition_fees_currency',
            field=models.ForeignKey(blank=True, help_text='Currency for tuition fees', limit_choices_to={'is_active': True, 'lookup_type__name': 'Currency'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualifications_by_currency', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='tuition_method',
            field=models.ForeignKey(blank=True, help_text='How tuition was funded (e.g., Self-funded, Company-sponsored)', limit_choices_to={'is_active': True, 'lookup_type__name': 'Tuition Method'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualifications_by_tuition_method', to='lookups.lookupvalue'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['status', 'category'], name='hr_competen_status_61dddf_idx'),
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['code'], name='hr_competen_code_286bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['name'], name='hr_competen_name_83434a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcompetencyrequirement',
            index=models.Index(fields=['job', 'competency'], name='hr_job_comp_job_id_f96a78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobcompetencyrequirement',
            unique_together={('job', 'competency')},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email_address'], name='person_email_a_6d3c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['national_id'], name='person_nationa_6a7bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_reference'], name='hr_contract_contrac_578eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['person'], name='hr_contract_person__a9725d_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_status'], name='hr_contract_contrac_c672fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('contract_end_date__gte', models.F('contract_start_date'))), name='contract_end_date_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0)), name='contract_basic_salary_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('contract_reference', 'effective_start_date')},
        ),
        migrations.AddIndex(
            model_name='competencyproficiency',
            index=models.Index(fields=['status', 'person', 'competency'], name='hr_competen_status_0db7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyproficiency',
            index=models.Index(fields=['person', 'date_from', 'date_to'], name='hr_competen_person__6d3b20_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyproficiency',
            index=models.Index(fields=['competency', 'proficiency_level'], name='hr_competen_compete_8b1c35_idx'),
        ),
        migrations.AddConstraint(
            model_name='competencyproficiency',
            constraint=models.UniqueConstraint(fields=('person', 'competency', 'date_from'), name='unique_person_competency_date'),
        ),
        migrations.AddConstraint(
            model_name='competencyproficiency',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='proficiency_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['person'], name='hr_assignme_person__3db681_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['business_group'], name='hr_assignme_busines_cd1cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignment_no'], name='hr_assignme_assignm_1f435c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['department'], name='hr_assignme_departm_f9cfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['job'], name='hr_assignme_job_id_d584fb_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['position'], name='hr_assignme_positio_85b3b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('work_end_time__gt', models.F('work_start_time')), ('work_start_time__isnull', True), ('work_end_time__isnull', True), _connector='OR'), name='assignment_work_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('assignment_no', 'effective_start_date')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['person', 'status'], name='person_addr_person__8fe71e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['person', 'is_primary'], name='person_addr_person__b046ac_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address_type', 'status'], name='person_addr_address_f1fbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'city'], name='person_addr_country_d04275_idx'),
        ),
        migrations.AddIndex(
            model_name='persontype',
            index=models.Index(fields=['base_type', 'is_active'], name='person_type_base_ty_d05520_idx'),
        ),
        migrations.AddConstraint(
            model_name='persontype',
            constraint=models.CheckConstraint(condition=models.Q(('base_type__in', ['APL', 'EMP', 'CWK', 'CON'])), name='valid_base_type'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['person', 'effective_start_date'], name='employee_person__862bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='employee_employe_6b6fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='employee_effecti_40f663_idx'),
        ),
        migrations.AddIndex(
            model_name='contingentworker',
            index=models.Index(fields=['person', 'effective_start_date'], name='contingent__person__f09915_idx'),
        ),
        migrations.AddIndex(
            model_name='contingentworker',
            index=models.Index(fields=['worker_number'], name='contingent__worker__347b82_idx'),
        ),
        migrations.AddIndex(
            model_name='contingentworker',
            index=models.Index(fields=['vendor_name'], name='contingent__vendor__1c2f82_idx'),
        ),
        migrations.AddIndex(
            model_name='contingentworker',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='contingent__effecti_f25715_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['person', 'effective_start_date'], name='contact_person__7d2627_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_number'], name='contact_contact_c6d450_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization_name'], name='contact_organiz_4aeb61_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['emergency_for_employee'], name='contact_emergen_550a88_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='contact_effecti_09d106_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['person', 'effective_start_date'], name='applicant_person__e5b6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['application_number'], name='applicant_applica_6a1ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['application_status'], name='applicant_applica_dec276_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='applicant_effecti_f958d7_idx'),
        ),
        migrations.AddIndex(
            model_name='persontypedffconfig',
            index=models.Index(fields=['person_type', 'is_active'], name='person_type_person__93274b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='persontypedffconfig',
            unique_together={('person_type', 'column_name'), ('person_type', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='positioncompetencyrequirement',
            index=models.Index(fields=['position', 'competency'], name='hr_position_positio_d0268b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='positioncompetencyrequirement',
            unique_together={('position', 'competency')},
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['status', 'person'], name='hr_qualific_status_3c21f7_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['person', 'qualification_status'], name='hr_qualific_person__e89670_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['qualification_type', 'qualification_status'], name='hr_qualific_qualifi_cd868f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='hr_qualific_effecti_501102_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('completed_percentage__isnull', True), models.Q(('completed_percentage__gte', 0), ('completed_percentage__lte', 100)), _connector='OR'), name='qualification_percentage_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end_date__isnull', True), ('effective_end_date__gte', models.F('effective_start_date')), _connector='OR'), name='qualification_effective_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('study_end_date__isnull', True), ('study_start_date__isnull', True), ('study_end_date__gte', models.F('study_start_date')), _connector='OR'), name='qualification_study_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('tuition_fees__isnull', True), ('tuition_fees_currency__isnull', False), _connector='OR'), name='qualification_fees_requires_currency'),
        ),
    ]
