# Generated by Django 5.2.8 on 2026-01-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_create_base_person_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='application_date',
        ),
    ]
