# Generated by Django 5.2.8 on 2026-01-26 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('person', '0004_remove_applicant_application_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencyproficiency',
            options={'ordering': ['person', 'competency', '-effective_start_date'], 'verbose_name': 'Competency Proficiency', 'verbose_name_plural': 'Competency Proficiencies'},
        ),
        migrations.RemoveConstraint(
            model_name='competencyproficiency',
            name='unique_person_competency_date',
        ),
        migrations.RemoveConstraint(
            model_name='competencyproficiency',
            name='proficiency_end_after_start',
        ),
        migrations.RemoveIndex(
            model_name='competencyproficiency',
            name='hr_competen_status_0db7e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='competencyproficiency',
            name='hr_competen_person__6d3b20_idx',
        ),
        migrations.RemoveField(
            model_name='competencyproficiency',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='competencyproficiency',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='competencyproficiency',
            name='status',
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='effective_end_date',
            field=models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True),
        ),
        migrations.AddField(
            model_name='competencyproficiency',
            name='effective_start_date',
            field=models.DateField(default='2000-01-01', help_text='Date this version becomes active'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='competencyproficiency',
            index=models.Index(fields=['person', 'effective_start_date', 'effective_end_date'], name='hr_competen_person__20f8e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='competencyproficiency',
            constraint=models.UniqueConstraint(fields=('person', 'competency', 'effective_start_date'), name='unique_person_competency_date'),
        ),
        migrations.AddConstraint(
            model_name='competencyproficiency',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end_date__isnull', True), ('effective_end_date__gte', models.F('effective_start_date')), _connector='OR'), name='proficiency_end_after_start'),
        ),
    ]
