# Generated by Django 4.2.7 on 2025-12-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_ap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apinvoice',
            name='base_currency_total',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='is_posted',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='posted_at',
        ),
    ]
