# Generated by Django 5.2.8 on 2025-12-08 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflowStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(help_text='1-based ordering of stages')),
                ('name', models.CharField(max_length=120)),
                ('decision_policy', models.CharField(choices=[('ALL', 'All must approve'), ('ANY', 'Any one can approve'), ('QUORUM', 'Quorum of approvals')], default='ALL', max_length=10)),
                ('quorum_count', models.PositiveIntegerField(blank=True, help_text='Required number of approvals for QUORUM policy', null=True)),
                ('required_role', models.CharField(blank=True, help_text='Optional user.role filter', max_length=50, null=True)),
                ('dynamic_filter_json', models.TextField(blank=True, help_text='JSON string for complex filtering logic', null=True)),
                ('allow_reject', models.BooleanField(default=True)),
                ('allow_delegate', models.BooleanField(default=False)),
                ('sla_hours', models.PositiveIntegerField(blank=True, help_text='Hours before SLA breach', null=True)),
                ('parallel_group', models.PositiveIntegerField(blank=True, help_text='Stages in same group run in parallel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_workflow_stage_template',
                'ordering': ['workflow_template', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('completed_stage_count', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('current_stage_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_instances', to='approval.approvalworkflowstagetemplate')),
            ],
            options={
                'db_table': 'approval_workflow_instance',
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='approval.approvalworkflowinstance')),
                ('stage_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_instances', to='approval.approvalworkflowstagetemplate')),
            ],
            options={
                'db_table': 'approval_workflow_stage_instance',
                'ordering': ['workflow_instance', 'stage_template__order_index'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('level_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_assignments', to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='approval.approvalworkflowstageinstance')),
            ],
            options={
                'db_table': 'approval_assignment',
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('delegate', 'Delegate'), ('comment', 'Comment')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggers_stage_completion', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='Null for system actions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='approval.approvalassignment')),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approval.approvalworkflowstageinstance')),
            ],
            options={
                'db_table': 'approval_action',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for this template', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('filter_field', models.CharField(blank=True, help_text="Optional field name on the model to filter by (e.g., 'transfer_type', 'invoice_type')", max_length=100, null=True)),
                ('filter_value', models.CharField(blank=True, help_text="Value that filter_field should match (e.g., 'FAR', 'PURCHASE')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='The model type this template applies to (e.g., BudgetTransfer, Invoice, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'approval_workflow_template',
                'ordering': ['content_type', '-version', 'code'],
            },
        ),
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='approval.approvalworkflowtemplate'),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approval.approvalworkflowtemplate'),
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='approval.approvalworkflowstageinstance')),
            ],
            options={
                'db_table': 'approval_delegation',
                'indexes': [models.Index(fields=['active', 'to_user'], name='approval_de_active_b84c30_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='approvalassignment',
            index=models.Index(fields=['user', 'status'], name='approval_as_user_id_8d2860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalassignment',
            unique_together={('stage_instance', 'user')},
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['stage_instance', 'action'], name='approval_ac_stage_i_6a6f11_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['user', 'created_at'], name='approval_ac_user_id_82e3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowstageinstance',
            index=models.Index(fields=['workflow_instance', 'status'], name='approval_wo_workflo_c1ea06_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowtemplate',
            index=models.Index(fields=['content_type', 'is_active'], name='approval_wo_content_954b22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowstagetemplate',
            unique_together={('workflow_template', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_wo_content_b96715_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['status', 'current_stage_template'], name='approval_wo_status_12cd7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowinstance',
            unique_together={('content_type', 'object_id')},
        ),
    ]
