# Generated by Django 6.0 on 2025-12-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hierarchy_level', models.IntegerField(default=0, help_text='Numeric level for hierarchical ordering (higher = more authority)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_user_level',
                'ordering': ['-hierarchy_level', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='approvalworkflowtemplate',
            name='approval_wo_content_082f81_idx',
        ),
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='required_user_level',
            field=models.ForeignKey(blank=True, help_text='If set, assignments will include users with this level', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_stage_templates', to='approval.xx_userlevel'),
        ),
        migrations.RemoveField(
            model_name='approvalworkflowtemplate',
            name='filter_field',
        ),
        migrations.RemoveField(
            model_name='approvalworkflowtemplate',
            name='filter_value',
        ),
    ]
