# Generated by Django 5.2.8 on 2025-12-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('job_roles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for system actions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='approval.approvalassignment'),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstageinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='approval.approvalworkflowinstance'),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='stage_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='approval.approvalworkflowstageinstance'),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='approval.approvalworkflowstageinstance'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approval.approvalworkflowstageinstance'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='required_role',
            field=models.ForeignKey(blank=True, help_text='Optional job role filter - only users with this job role can approve', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_roles.jobrole'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstageinstance',
            name='stage_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_instances', to='approval.approvalworkflowstagetemplate'),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='current_stage_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_instances', to='approval.approvalworkflowstagetemplate'),
        ),
        migrations.AddField(
            model_name='approvalworkflowtemplate',
            name='content_type',
            field=models.ForeignKey(help_text='The model type this template applies to (e.g., BudgetTransfer, Invoice, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='approval.approvalworkflowtemplate'),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approval.approvalworkflowtemplate'),
        ),
        migrations.AddIndex(
            model_name='approvaldelegation',
            index=models.Index(fields=['active', 'to_user'], name='approval_de_active_b84c30_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalassignment',
            index=models.Index(fields=['user', 'status'], name='approval_as_user_id_8d2860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalassignment',
            unique_together={('stage_instance', 'user')},
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['stage_instance', 'action'], name='approval_ac_stage_i_6a6f11_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['user', 'created_at'], name='approval_ac_user_id_82e3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowstageinstance',
            index=models.Index(fields=['workflow_instance', 'status'], name='approval_wo_workflo_c1ea06_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowtemplate',
            index=models.Index(fields=['content_type', 'is_active'], name='approval_wo_content_954b22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowstagetemplate',
            unique_together={('workflow_template', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_wo_content_b96715_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['status', 'current_stage_template'], name='approval_wo_status_12cd7d_idx'),
        ),
    ]
