# Generated by Django 6.0 on 2025-12-08 11:42

import django.db.models.deletion
from django.db import migrations, models
from django.db import connection


def remove_index_if_exists(apps, schema_editor):
    """Remove index only if it exists"""
    with connection.cursor() as cursor:
        # Check if index exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='approval_wo_content_082f81_idx'
        """)
        if cursor.fetchone():
            # Index exists, remove it
            cursor.execute("DROP INDEX approval_wo_content_082f81_idx")


def remove_fields_if_exist(apps, schema_editor):
    """Remove fields only if they exist"""
    with connection.cursor() as cursor:
        # Get table info for approvalworkflowtemplate
        cursor.execute("PRAGMA table_info(approval_approvalworkflowtemplate)")
        columns = [row[1] for row in cursor.fetchall()]
        
        # Check if we need to recreate the table without these columns
        if 'filter_field' in columns or 'filter_value' in columns:
            # Fields exist, need to remove them by recreating table
            # Get existing data
            cursor.execute("SELECT * FROM approval_approvalworkflowtemplate")
            # This is complex for SQLite, so we'll skip it and let Django handle it
            # The issue is the fields don't exist in the current DB state
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hierarchy_level', models.IntegerField(default=0, help_text='Numeric level for hierarchical ordering (higher = more authority)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_user_level',
                'ordering': ['-hierarchy_level', 'name'],
            },
        ),
        migrations.RunPython(remove_index_if_exists, migrations.RunPython.noop),
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='required_user_level',
            field=models.ForeignKey(blank=True, help_text='If set, assignments will include users with this level', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_stage_templates', to='approval.xx_userlevel'),
        ),
        migrations.RemoveField(
            model_name='approvalworkflowtemplate',
            name='filter_field',
        ),
        migrations.RemoveField(
            model_name='approvalworkflowtemplate',
            name='filter_value',
        ),
    ]
