# Generated by Django 6.0 on 2025-12-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_xx_userlevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalworkflowstagetemplate',
            name='required_user_level',
        ),
    ]
