# Generated by Django 6.0 on 2025-12-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_testinvoice_testpurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldelegation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='stage_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='approval.approvalworkflowstageinstance'),
        ),
    ]
