# Generated by Django 6.0 on 2025-12-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_approvaldelegation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalworkflowinstance',
            unique_together=set(),
        ),
    ]
