# Generated by Django 6.0 on 2025-12-10 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_alter_approvalworkflowinstance_unique_together'),
        ('job_roles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xx_UserLevel',
        ),
        migrations.AlterField(
            model_name='approvalworkflowstagetemplate',
            name='required_role',
            field=models.ForeignKey(blank=True, help_text='Optional job role filter - only users with this job role can approve', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_roles.jobrole'),
        ),
    ]
