# Generated by Django 5.2.8 on 2025-12-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_delete_xx_userlevel_and_more'),
        ('job_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflowstagetemplate',
            name='required_role',
            field=models.ForeignKey(blank=True, help_text='Optional job role filter - only users with this job role can approve', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_roles.jobrole'),
        ),
    ]
