# Generated by Django 6.0 on 2026-01-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_alter_approvalworkflowstagetemplate_required_role'),
    ]

    operations = [
    ]
