# Generated by Django 4.2.7 on 2025-12-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_core', '0002_country_currency_exchange_rate_to_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('country', models.ForeignKey(blank=True, help_text='ISO 2-letter country code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_customers', to='finance_core.country')),
            ],
            options={
                'db_table': 'ar_customer',
            },
        ),
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval workflow status', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status of the invoice', max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice subtotal (before tax)', max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total tax amount', max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice total (subtotal + tax)', max_digits=14, null=True)),
                ('country', models.ForeignKey(blank=True, help_text='Tax country for this invoice (defaults to customer country)', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance_core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='finance_core.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_ar.customer')),
            ],
            options={
                'db_table': 'ar_arinvoice',
            },
        ),
    ]
