# Generated by Django 6.0 on 2025-12-07 12:14

import Finance.core.base_models
import Finance.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_core', '0003_alter_taxrate_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(blank=True, help_text='ISO 2-letter country code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_partners', to='finance_core.country')),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
                'db_table': 'business_partner',
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_in_details', models.TextField(blank=True, help_text='Detailed delivery address')),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='finance_businesspartner.businesspartner')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
            bases=(Finance.core.base_models.ChildModelMixin, Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OneTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/VAT number', max_length=50)),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='one_time_supplier', to='finance_businesspartner.businesspartner')),
            ],
            options={
                'verbose_name': 'One Time Supplier',
                'verbose_name_plural': 'One Time Suppliers',
                'db_table': 'one_time_supplier',
            },
            bases=(Finance.core.base_models.ChildModelMixin, Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('vat_number', models.CharField(blank=True, help_text='VAT/Tax registration number (TRN)', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='Alternative tax ID', max_length=50)),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='finance_businesspartner.businesspartner')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
            },
            bases=(Finance.core.base_models.ChildModelMixin, Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
    ]
