# Generated by Django 5.2.8 on 2025-12-29 15:28

import Finance.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_gl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='set_default_combinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('AP_INVOICE', 'Accounts Payable Invoice'), ('AR_INVOICE', 'Accounts Receivable Invoice')], help_text='Type of transaction for which the default combination is set', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this default is active. Auto-deactivated if segment types change.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this default combination was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this default combination was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this default combination', on_delete=django.db.models.deletion.PROTECT, related_name='default_combinations_created', to=settings.AUTH_USER_MODEL)),
                ('segment_combination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_gl.xx_segment_combination')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this default combination', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_combinations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Default Segment Combination',
                'verbose_name_plural': 'Default Segment Combinations',
                'ordering': ['transaction_type'],
            },
            bases=(Finance.core.models.ProtectedDeleteMixin, models.Model),
        ),
    ]
