# Generated by Django 5.2.8 on 2026-01-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Period name (e.g., 'January 2026')", max_length=100)),
                ('start_date', models.DateField(help_text='Period start date')),
                ('end_date', models.DateField(help_text='Period end date')),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year (e.g., 2026)')),
                ('period_number', models.IntegerField(help_text='Period number within fiscal year (1-13)')),
                ('is_adjustment_period', models.BooleanField(default=False, help_text='True if this is an adjustment period (typically period 13)')),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'finance_period',
                'ordering': ['fiscal_year', 'period_number'],
                'indexes': [models.Index(fields=['fiscal_year', 'period_number'], name='finance_per_fiscal__8420fd_idx'), models.Index(fields=['start_date', 'end_date'], name='finance_per_start_d_4b0daa_idx')],
                'unique_together': {('fiscal_year', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='gl_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', help_text='State of the GL module for this period', max_length=10)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gl_period', to='period.period')),
            ],
            options={
                'verbose_name': 'GL Period',
                'verbose_name_plural': 'GL Periods',
                'db_table': 'finance_gl_period',
            },
        ),
        migrations.CreateModel(
            name='ar_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', help_text='State of the AR module for this period', max_length=10)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_period', to='period.period')),
            ],
            options={
                'verbose_name': 'AR Period',
                'verbose_name_plural': 'AR Periods',
                'db_table': 'finance_ar_period',
            },
        ),
        migrations.CreateModel(
            name='ap_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', help_text='State of the AP module for this period', max_length=10)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ap_period', to='period.period')),
            ],
            options={
                'verbose_name': 'AP Period',
                'verbose_name_plural': 'AP Periods',
                'db_table': 'finance_ap_period',
            },
        ),
    ]
