# Generated by Django 6.0 on 2025-12-07 12:14

import Finance.Invoice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_businesspartner', '0001_initial'),
        ('finance_core', '0003_alter_taxrate_rate'),
        ('finance_gl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField()),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval workflow status', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status of the invoice', max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice subtotal (before tax)', max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total tax amount', max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice total (subtotal + tax)', max_digits=14, null=True)),
                ('business_partner', models.ForeignKey(help_text='The business partner associated with this invoice (auto-set from child type)', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_businesspartner.businesspartner')),
                ('country', models.ForeignKey(blank=True, help_text='Tax country for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_core.currency')),
                ('gl_distributions', models.ForeignKey(help_text='GL Journal Entry for this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_gl.journalentry')),
            ],
            options={
                'verbose_name': 'General Invoice',
                'verbose_name_plural': 'General Invoices',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance_invoice.invoice')),
            ],
            options={
                'db_table': 'invoice_item',
            },
        ),
        migrations.CreateModel(
            name='OneTimeSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OneTimeSuppliers', to='finance_invoice.invoice')),
                ('one_time_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_time_suppliers_invoices', to='finance_businesspartner.onetime')),
            ],
            options={
                'verbose_name': 'One-Time Supplier',
                'verbose_name_plural': 'One-Time Suppliers',
                'db_table': 'OneTimeSupplier',
            },
            bases=(Finance.Invoice.models.InvoiceChildModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AP_Invoice',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ap_invoice', serialize=False, to='finance_invoice.invoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance_businesspartner.supplier')),
            ],
            options={
                'verbose_name': 'AP Invoice',
                'verbose_name_plural': 'AP Invoices',
                'db_table': 'ap_invoice',
            },
            bases=(Finance.Invoice.models.InvoiceChildModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AR_Invoice',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ar_invoice', serialize=False, to='finance_invoice.invoice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='finance_businesspartner.customer')),
            ],
            options={
                'verbose_name': 'AR Invoice',
                'verbose_name_plural': 'AR Invoices',
                'db_table': 'ar_invoice',
            },
            bases=(Finance.Invoice.models.InvoiceChildModelMixin, models.Model),
        ),
    ]
