# Generated by Django 4.2.7 on 2025-12-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_core', '0002_country_currency_exchange_rate_to_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal name of supplier/vendor', max_length=128)),
                ('legal_name', models.CharField(blank=True, help_text='Full legal entity name (if different from name)', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('vat_number', models.CharField(blank=True, help_text='VAT/Tax registration number (TRN)', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='Alternative tax ID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this vendor')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='finance_core.country')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='APInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField()),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval workflow status', max_length=20)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether invoice is posted to GL')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status of the invoice', max_length=20)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate used when posting (invoice currency to base currency)', max_digits=18, null=True)),
                ('base_currency_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in base currency', max_digits=14, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice subtotal (before tax)', max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total tax amount', max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice total (subtotal + tax)', max_digits=14, null=True)),
                ('country', models.ForeignKey(blank=True, help_text='Tax country for this invoice (defaults to supplier country)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance_core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance_core.currency')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_invoice.supplier')),
            ],
            options={
                'db_table': 'ap_apinvoice',
            },
        ),
    ]
