# Generated by Django 6.0 on 2025-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far (cannot exceed total)', max_digits=14),
        ),
    ]
