# Generated by Django 6.0 on 2025-12-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0002_add_paid_amount_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was approved', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was rejected', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was submitted for approval', null=True),
        ),
    ]
