# Generated by Django 5.2.8 on 2025-12-05 16:07

import Finance.Invoice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_businesspartner', '0001_initial'),
        ('finance_core', '0002_country_currency_exchange_rate_to_base_currency_and_more'),
        ('finance_gl', '0001_initial'),
        ('finance_invoice', '0003_delete_old_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genral_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval workflow status', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status of the invoice', max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice subtotal (before tax)', max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total tax amount', max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice total (subtotal + tax)', max_digits=14, null=True)),
                ('country', models.ForeignKey(blank=True, help_text='Tax country for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_core.currency')),
                ('gl_distributions', models.ForeignKey(help_text='GL Journal Entry for this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_gl.journalentry')),
            ],
            options={
                'verbose_name': 'General Invoice',
                'verbose_name_plural': 'General Invoices',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='one_use_supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.TextField(blank=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('supplier_phone', models.CharField(blank=True, max_length=50)),
                ('supplier_tax_id', models.CharField(blank=True, help_text='Tax ID/VAT number', max_length=50)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_use_suppliers', to='finance_invoice.genral_invoice')),
            ],
            options={
                'verbose_name': 'One-Time Supplier',
                'verbose_name_plural': 'One-Time Suppliers',
                'db_table': 'one_use_supplier',
            },
            bases=(Finance.Invoice.models.InvoiceChildModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AP_Invoice',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ap_invoice', serialize=False, to='finance_invoice.genral_invoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance_businesspartner.supplier')),
            ],
            options={
                'verbose_name': 'AP Invoice',
                'verbose_name_plural': 'AP Invoices',
                'db_table': 'ap_invoice',
            },
            bases=(Finance.Invoice.models.InvoiceChildModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AR_Invoice',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ar_invoice', serialize=False, to='finance_invoice.genral_invoice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='finance_businesspartner.customer')),
            ],
            options={
                'verbose_name': 'AR Invoice',
                'verbose_name_plural': 'AR Invoices',
                'db_table': 'ar_invoice',
            },
            bases=(Finance.Invoice.models.InvoiceChildModelMixin, models.Model),
        ),
    ]
