# Generated by Django 5.2.8 on 2025-12-31 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0003_invoice_approved_at_invoice_rejected_at_and_more'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap_invoice',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, help_text='Goods Receipt that this invoice was created from (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='receiving.goodsreceipt'),
        ),
    ]
