# Generated by Django 5.2.8 on 2026-01-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0004_ap_invoice_goods_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap_invoice',
            name='variance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Variance percentage between PO total and Invoice total: ((invoice_total - po_total) / po_total) * 100', max_digits=10, null=True),
        ),
    ]
