# Generated by Django 5.2.8 on 2025-12-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_businesspartner', '0001_initial'),
        ('finance_core', '0002_country_currency_exchange_rate_to_base_currency_and_more'),
        ('finance_invoice', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ap_invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ar_invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genral_invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='one_use_supplier',
            options={},
        ),
        migrations.RemoveField(
            model_name='one_use_supplier',
            name='supplier_email',
        ),
        migrations.RemoveField(
            model_name='one_use_supplier',
            name='supplier_phone',
        ),
        migrations.RemoveField(
            model_name='one_use_supplier',
            name='supplier_tax_id',
        ),
        migrations.AlterField(
            model_name='ap_invoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finance_invoice.genral_invoice'),
        ),
        migrations.AlterField(
            model_name='ap_invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_businesspartner.supplier'),
        ),
        migrations.AlterField(
            model_name='ar_invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_businesspartner.customer'),
        ),
        migrations.AlterField(
            model_name='ar_invoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finance_invoice.genral_invoice'),
        ),
        migrations.AlterField(
            model_name='genral_invoice',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Tax country for this invoice (defaults to supplier country)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance_core.country'),
        ),
        migrations.AlterField(
            model_name='genral_invoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance_core.currency'),
        ),
        migrations.AlterField(
            model_name='one_use_supplier',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_invoice.genral_invoice'),
        ),
        migrations.AlterField(
            model_name='one_use_supplier',
            name='supplier_address',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='ap_invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ar_invoice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='one_use_supplier',
            table=None,
        ),
    ]
