# Generated by Django 6.0 on 2025-12-05 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_businesspartner', '0001_initial'),
        ('finance_core', '0002_country_currency_exchange_rate_to_base_currency_and_more'),
        ('finance_invoice', '0005_alter_ap_invoice_options_alter_ar_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ap_invoice',
            options={'verbose_name': 'AP Invoice', 'verbose_name_plural': 'AP Invoices'},
        ),
        migrations.AlterModelOptions(
            name='ar_invoice',
            options={'verbose_name': 'AR Invoice', 'verbose_name_plural': 'AR Invoices'},
        ),
        migrations.AlterModelOptions(
            name='genral_invoice',
            options={'verbose_name': 'General Invoice', 'verbose_name_plural': 'General Invoices'},
        ),
        migrations.AlterModelOptions(
            name='one_use_supplier',
            options={'verbose_name': 'One-Time Supplier', 'verbose_name_plural': 'One-Time Suppliers'},
        ),
        migrations.AddField(
            model_name='one_use_supplier',
            name='supplier_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='one_use_supplier',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='one_use_supplier',
            name='supplier_tax_id',
            field=models.CharField(blank=True, help_text='Tax ID/VAT number', max_length=50),
        ),
        migrations.AlterField(
            model_name='ap_invoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ap_invoice', serialize=False, to='finance_invoice.genral_invoice'),
        ),
        migrations.AlterField(
            model_name='ap_invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_invoices', to='finance_businesspartner.supplier'),
        ),
        migrations.AlterField(
            model_name='ar_invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='finance_businesspartner.customer'),
        ),
        migrations.AlterField(
            model_name='ar_invoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ar_invoice', serialize=False, to='finance_invoice.genral_invoice'),
        ),
        migrations.AlterField(
            model_name='genral_invoice',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Tax country for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_core.country'),
        ),
        migrations.AlterField(
            model_name='genral_invoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance_core.currency'),
        ),
        migrations.AlterField(
            model_name='one_use_supplier',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_use_suppliers', to='finance_invoice.genral_invoice'),
        ),
        migrations.AlterField(
            model_name='one_use_supplier',
            name='supplier_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='ap_invoice',
            table='ap_invoice',
        ),
        migrations.AlterModelTable(
            name='ar_invoice',
            table='ar_invoice',
        ),
        migrations.AlterModelTable(
            name='one_use_supplier',
            table='one_use_supplier',
        ),
    ]
