# Generated by Django 5.2.8 on 2026-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0005_ap_invoice_variance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Manually entered invoice number (required)', max_length=50, null=True, unique=True),
        ),
    ]
