# Generated by Django 5.2.8 on 2026-02-02 10:57

from django.db import migrations


def backfill_invoice_numbers(apps, schema_editor):
    """
    Backfill invoice_number for existing invoices.
    Uses pattern: {prefix_code}-{id} or just {id} if no prefix.
    """
    Invoice = apps.get_model('finance_invoice', 'Invoice')
    
    for invoice in Invoice.objects.filter(invoice_number__isnull=True):
        if invoice.prefix_code:
            invoice.invoice_number = f"{invoice.prefix_code}-{invoice.id}"
        else:
            invoice.invoice_number = str(invoice.id)
        invoice.save(update_fields=['invoice_number'])


def reverse_backfill(apps, schema_editor):
    """
    Reverse operation - set invoice_number back to null.
    """
    Invoice = apps.get_model('finance_invoice', 'Invoice')
    Invoice.objects.all().update(invoice_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0006_invoice_invoice_number'),
    ]

    operations = [
        migrations.RunPython(backfill_invoice_numbers, reverse_backfill),
    ]
