# Generated by Django 6.0 on 2025-12-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core', '0002_country_currency_exchange_rate_to_base_currency_and_more'),
        ('finance_gl', '0001_initial'),
        ('finance_invoice', '0006_alter_ap_invoice_options_alter_ar_invoice_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genral_Invoice',
            new_name='Invoice',
        ),
    ]
