# Generated by Django 5.2.8 on 2026-02-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_invoice', '0007_backfill_invoice_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(help_text='Manually entered invoice number (required)', max_length=50, unique=True),
        ),
    ]
