# Generated by Django 5.2.8 on 2026-01-21 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lookup_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Spouse')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive values hidden from dropdowns')),
                ('lookup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='lookups.lookuptype')),
                ('parent', models.ForeignKey(blank=True, help_text='For hierarchical lookups (e.g., Cairo → Egypt)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lookups.lookupvalue')),
            ],
            options={
                'db_table': 'lookup_value',
                'ordering': ['lookup_type', 'sequence', 'name'],
                'unique_together': {('lookup_type', 'name')},
            },
        ),
    ]
