# Generated by Django 5.2.8 on 2025-12-11 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique identifier for the action (e.g., 'view', 'create', 'edit', 'delete')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'db_table': 'actions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'db_table': 'job_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique identifier for the page (e.g., 'invoice_management')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_actions', to='job_roles.action')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_actions', to='job_roles.page')),
            ],
            options={
                'verbose_name': 'Page Action',
                'verbose_name_plural': 'Page Actions',
                'db_table': 'page_actions',
                'ordering': ['page__display_name', 'action__name'],
            },
        ),
        migrations.CreateModel(
            name='UserActionDenial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_denials', to='job_roles.pageaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_denials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Action Denial',
                'verbose_name_plural': 'User Action Denials',
                'db_table': 'user_action_denials',
                'ordering': ['user__email', 'page_action__page__display_name'],
            },
        ),
        migrations.CreateModel(
            name='JobRolePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_role_pages', to='job_roles.jobrole')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='job_roles.page')),
            ],
            options={
                'verbose_name': 'Job Role Page',
                'verbose_name_plural': 'Job Role Pages',
                'db_table': 'job_role_pages',
                'ordering': ['job_role__name', 'page__display_name'],
                'indexes': [models.Index(fields=['job_role', 'page'], name='job_role_pa_job_rol_e27ef1_idx')],
                'unique_together': {('job_role', 'page')},
            },
        ),
        migrations.AddIndex(
            model_name='pageaction',
            index=models.Index(fields=['page', 'action'], name='page_action_page_id_5d97d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageaction',
            unique_together={('page', 'action')},
        ),
        migrations.AddIndex(
            model_name='useractiondenial',
            index=models.Index(fields=['user', 'page_action'], name='user_action_user_id_9e77bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useractiondenial',
            unique_together={('user', 'page_action')},
        ),
    ]
