# Generated by Django 5.2.8 on 2025-12-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique identifier for the action (e.g., 'view', 'create', 'edit', 'delete')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'db_table': 'actions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'db_table': 'job_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique identifier for the page (e.g., 'invoice_management')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='JobRolePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_role_pages', to='job_roles.jobrole')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='job_roles.page')),
            ],
            options={
                'verbose_name': 'Job Role Page',
                'verbose_name_plural': 'Job Role Pages',
                'db_table': 'job_role_pages',
                'ordering': ['job_role__name', 'page__display_name'],
            },
        ),
        migrations.CreateModel(
            name='PageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_actions', to='job_roles.action')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_actions', to='job_roles.page')),
            ],
            options={
                'verbose_name': 'Page Action',
                'verbose_name_plural': 'Page Actions',
                'db_table': 'page_actions',
                'ordering': ['page__display_name', 'action__name'],
            },
        ),
        migrations.CreateModel(
            name='UserActionDenial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denial_reason', models.TextField(blank=True, help_text='Optional reason for the denial', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_denials', to='job_roles.pageaction')),
            ],
            options={
                'verbose_name': 'User Action Denial',
                'verbose_name_plural': 'User Action Denials',
                'db_table': 'user_action_denials',
                'ordering': ['user__email', 'page_action__page__display_name'],
            },
        ),
    ]
