# Generated by Django 5.2.8 on 2025-12-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractiondenial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_denials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobrolepage',
            index=models.Index(fields=['job_role', 'page'], name='job_role_pa_job_rol_e27ef1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrolepage',
            unique_together={('job_role', 'page')},
        ),
        migrations.AddIndex(
            model_name='pageaction',
            index=models.Index(fields=['page', 'action'], name='page_action_page_id_5d97d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageaction',
            unique_together={('page', 'action')},
        ),
        migrations.AddIndex(
            model_name='useractiondenial',
            index=models.Index(fields=['user', 'page_action'], name='user_action_user_id_9e77bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useractiondenial',
            unique_together={('user', 'page_action')},
        ),
    ]
