# Generated by Django 5.2.8 on 2025-12-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractiondenial',
            name='denial_reason',
            field=models.TextField(blank=True, help_text='Optional reason for the denial', null=True),
        ),
    ]
