# Generated by Django 5.2.8 on 2025-12-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_roles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='action',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobrolepage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pageaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pageaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='useractiondenial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useractiondenial',
            name='updated_at',
        ),
    ]
