# Generated by Django 5.2.8 on 2026-01-07 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_roles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
            ],
            options={
                'verbose_name': 'User Job Role',
                'verbose_name_plural': 'User Job Roles',
                'db_table': 'user_job_roles',
                'ordering': ['-effective_start_date', 'job_role__name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified')),
                ('effective_start_date', models.DateField(help_text='Date this version becomes active')),
                ('effective_end_date', models.DateField(blank=True, help_text='Date this version ends. NULL = currently active', null=True)),
                ('permission_type', models.CharField(choices=[('deny', 'Deny'), ('grant', 'Grant')], db_index=True, default='deny', help_text="'deny' removes permission, 'grant' adds permission", max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for granting/denying this permission', null=True)),
            ],
            options={
                'verbose_name': 'User Permission Override',
                'verbose_name_plural': 'User Permission Overrides',
                'db_table': 'user_permission_overrides',
                'ordering': ['-effective_start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='useractiondenial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='useractiondenial',
            name='page_action',
        ),
        migrations.RemoveField(
            model_name='useractiondenial',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['code'], 'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='jobrolepage',
            options={'ordering': ['job_role__name', 'page__sort_order', 'page__name'], 'verbose_name': 'Job Role Page', 'verbose_name_plural': 'Job Role Pages'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='pageaction',
            options={'ordering': ['page__name', 'action__code'], 'verbose_name': 'Page Action', 'verbose_name_plural': 'Page Actions'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='display_name',
        ),
        migrations.AddField(
            model_name='action',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Unique identifier for the action (e.g., 'view', 'create', 'edit', 'delete')", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='action',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Parent role for permission inheritance (child gets parent + own permissions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='job_roles.jobrole'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority role wins in permission conflicts'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Record status. Set to INACTIVE instead of deleting.', max_length=10),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrolepage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrolepage',
            name='inherit_to_children',
            field=models.BooleanField(default=True, help_text='If TRUE, access cascades to all descendant pages'),
        ),
        migrations.AddField(
            model_name='jobrolepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified'),
        ),
        migrations.AddField(
            model_name='jobrolepage',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Unique identifier for the page (e.g., 'hr_employee')", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='module_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Owning module code: hr, finance, procurement, core', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, help_text='Parent page for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_pages', to='job_roles.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display in menus (lower = first)'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(help_text="Human-readable name shown in UI (e.g., 'View', 'Create', 'Edit', 'Delete')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified'),
        ),
        migrations.AlterField(
            model_name='jobrolepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text="Human-readable name shown in UI (e.g., 'HR - Employee Management')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified'),
        ),
        migrations.AlterField(
            model_name='pageaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='pageaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last modified'),
        ),
        migrations.AddIndex(
            model_name='jobrole',
            index=models.Index(fields=['status', 'name'], name='job_roles_status_c2901e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrole',
            index=models.Index(fields=['parent_role', 'status'], name='job_roles_parent__ae60cb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrolepage',
            index=models.Index(fields=['job_role', 'inherit_to_children'], name='job_role_pa_job_rol_2bbc93_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['module_code'], name='pages_module__1e31c1_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['parent_page', 'sort_order'], name='pages_parent__96ba89_idx'),
        ),
        migrations.AddField(
            model_name='userjobrole',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userjobrole',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_roles', to='job_roles.jobrole'),
        ),
        migrations.AddField(
            model_name='userjobrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userjobrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='page_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='job_roles.pageaction'),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserActionDenial',
        ),
        migrations.AddIndex(
            model_name='userjobrole',
            index=models.Index(fields=['user', 'effective_start_date'], name='user_job_ro_user_id_ff51fa_idx'),
        ),
        migrations.AddIndex(
            model_name='userjobrole',
            index=models.Index(fields=['user', 'job_role', 'effective_start_date'], name='user_job_ro_user_id_8e17de_idx'),
        ),
        migrations.AddIndex(
            model_name='userjobrole',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='user_job_ro_effecti_ac9938_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['user', 'page_action', 'permission_type'], name='user_permis_user_id_5ebb96_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['user', 'permission_type', 'effective_start_date'], name='user_permis_user_id_565ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermissionoverride',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='user_permis_effecti_39e2e2_idx'),
        ),
    ]
