# Generated by Django 5.2.8 on 2026-01-07 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_roles', '0003_userjobrole_userpermissionoverride_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
