# Generated by Django 5.2.8 on 2026-01-07 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_roles', '0004_alter_userjobrole_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobrole',
            name='job_roles_status_c2901e_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobrole',
            name='job_roles_parent__ae60cb_idx',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='status',
        ),
        migrations.AddIndex(
            model_name='jobrole',
            index=models.Index(fields=['name'], name='job_roles_name_1962ea_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrole',
            index=models.Index(fields=['parent_role'], name='job_roles_parent__028770_idx'),
        ),
    ]
